### ISSUE TITLE
New "verification" breaks login

### ISSUE THREAD

**Issue by DreckSoft** [Second-Hand-Friends/kleinanzeigen-bot#104]
Kleinanzeigen really starts to suck. First login captcha, then session expiration after like an hour, now login verification by mail.

![Screenshot_20220910_123332](https://user-images.githubusercontent.com/68750712/189479555-dd78506c-d5ef-4235-9d73-957c8807e773.png)

If you get this message logon will always fail with the script. You cannot get the verification links and paste it within a few seconds.

**Comment by sebthom** [comment]
I cannot reproduce this. Login and publishing works fine for me.

**Comment by wrkceuvxex** [comment]
In the config.yaml set
  use_private_window: **false**

Worked for me.

**Comment by DreckSoft** [comment]
It could be that Kleinanzeigen disabled the feature again. At least it no longer appears on the "regular" login. I'll check when republishing the next time.
