### ISSUE TITLE
Updating existing ads

### ISSUE THREAD

**Issue by sbboli** [Second-Hand-Friends/kleinanzeigen-bot#105]
Is there any way, to automatically update the ad?
Lets say you want to lower the price or add to the items description.

I understand that you can force the creation of a new ad, but it can be helpful to keep the likes/favourites of potential buyers (they might receive a notification about the change) and also doesn't add to the anzeigen-quota.

Cheers

**Comment by sebthom** [comment]
This is not implemented. PRs welcome.
