### ISSUE TITLE
0.1.dev1+ged09098: Element not found or not clickable

### ISSUE THREAD

**Issue by jniggemann** [Second-Hand-Friends/kleinanzeigen-bot#109]
Reproducible messasge `NoSuchElementException: Message: Element xpath='//select[@id='priceType']' not found or not clickable` regardless of the ads I try to post.

**Comment by tegger2000** [comment]
i got the same error
it seems the ID changed to "post-ad-frontend-price", could this be ?

**Comment by sebthom** [comment]
Duplicate of #106
