### ISSUE TITLE
Adjust to frontend changes

### ISSUE THREAD

**Issue by ckocyigit** [Second-Hand-Friends/kleinanzeigen-bot#117]
Again it seems like ebay has changed their frontend a bit for price and pricetype.

I thought about just searching for the priceType select by extending via Xpath OR's something like:

`$x("//select[@id='price-type-react'] | //select[@id='micro-frontend-price-type'] | //select[@id='priceType']")`
However this returns the new pricetype object with id "micro-frontend-price-type" and the very first one with id "priceType" which is unclickable.
`(2) [select#micro-frontend-price-type.jsx-958121740, select#priceType]`

**Comment by DenisLanz** [comment]
Stumbled over the same issue. The input id changes after changing the category. Nesting the exceptions did the trick for me, not sure if that's well written python, though: 

```python
 except NoSuchElementException as ex:
                try: 
                    self.web_select(By.XPATH, "//select[@id='micro-frontend-price-type']", price_type)
                    if safe_get(ad_cfg, "price"):
                        self.web_input(By.ID, "micro-frontend-price", ad_cfg["price"])
                except NoSuchElementException as ex:
                      # code for old HTML version can be removed at one point in future
                    self.web_select(By.XPATH, "//select[@id='priceType']", price_type)
                    if safe_get(ad_cfg, "price"):
                        self.web_input(By.ID, "pstad-price", ad_cfg["price"])
```

don't have the time to create a PR today but I can give it a shot if @sebthom isn't faster.

**Comment by ckocyigit** [comment]
I've had the exact same changes in a PR before. 

Does anyone have a more future-proof solution for this. I mean ebay changed this fields ID like 3 times in 2 month 😃

**Comment by DenisLanz** [comment]
It'll become stable when Kleinanzeigen finished their re-implementation/a-b testing. 😉
