### ISSUE TITLE
[feature] request: ad_*.yaml switch to force update

### ISSUE THREAD

**Issue by Tschak77** [Second-Hand-Friends/kleinanzeigen-bot#12]
Would it be possible to have an switch at the ad_*.yaml config to force the renew only once and toggle the switch after done, because of for example data update. Of course it would be also work to change the date but it would be easier to have an switch.

**Comment by sebthom** [comment]
> @sebthom It would be also good to have this switch only in the add config file. Because I want only update one ad, because with other ad I already in contact with some buyers and want avoid to delete them.

you can try to set the republication_interval of the ad in question to 0 or -1. I haven't tried that myself.

**Comment by Tschak77** [comment]
@sebthom Thanks -1 works but not 0. But maybe we could still think about a switch in the ad yaml config. Like Update ones true and after this is done the program change this automatically back to false.

**Comment by sebthom** [comment]
@Tschak77 another option could be that you simply remove the `updated_on` field of the ads you want to force update on next run.
