### ISSUE TITLE
Instantly deactivated my account

### ISSUE THREAD

**Issue by muenznej** [Second-Hand-Friends/kleinanzeigen-bot#130]
Hi there, 

I just wanted to test your tool and i created a new account for it.
The moment i let the bot login the account got disabled ... 
Any tipps on why exactly this happend, how to proceed and how to circumvent this? Will this happen with my old account as well? :<

Best

**Comment by sebthom** [comment]
I know they have mechanisms/heuristics in place to prevent creation of fake accounts. So it might be related to the email address provider or personal data you entered (name, address, etc) and not to the bot. at least I haven't heard about anything like this before.

**Comment by muenznej** [comment]
Hey there, thx for your fast reply.

It can only be caused by the autolog in failing too fast/multiple times with the captcha and the infamous cookies "allow/deny" pop up. I didnt even reach the publishing step. I ll try again later. The  email is gmail btw and i activated it via phone number so, thats not what caused the lock up.

**Comment by jniggemann** [comment]
Kleinanzeigen is kind of notorious for instantly locking accounts that are newly created. I think the exact reason hasn't been found but I read that happens quite often.
