### ISSUE TITLE
[feature] Extend the download action with `download all`

### ISSUE THREAD

**Issue by provinzio** [Second-Hand-Friends/kleinanzeigen-bot#131]
It's currently possible to download a single ad by handing the ad id. To make republishing of all existings ads easier, I propose to extend the function to something like "download --all".

As I like to create and update my ads in the web browser by hand, it's not an option for me to work with the config files for that.

After having this, it might be an ease to combine the functions like "download all, archive/clear inactive ad configs, republish" to avoid multiple logins/captchas.

------

@sebthom @PhilK-7 

Is something of that kind currently in progress? Any arguments against my proposal? I'd like to contribute where whished.

**Comment by sebthom** [comment]
This sounds useful. I am not aware of anything like this being developed right now. @PhilK-7 WDYT?

**Comment by PhilK-7** [comment]
I think it is a logical evolution from this feature, and could be very useful. I made a new fork and going to implement it.
