### ISSUE TITLE
Problem with downloading ads (Path not found ...)

### ISSUE THREAD

**Issue by Raketenphysik** [Second-Hand-Friends/kleinanzeigen-bot#136]
Trying to download ads I get the following error message:

<code>[ERROR] Traceback (most recent call last):
  File "kleinanzeigen_bot\__main__.py", line 8, in <module>
  File "kleinanzeigen_bot\__init__.py", line 859, in main
  File "kleinanzeigen_bot\__init__.py", line 117, in run
  File "kleinanzeigen_bot\__init__.py", line 824, in download_ad_page
FileNotFoundError: [WinError 3] Das System kann den angegebenen Pfad nicht finden: ''

[1332] Failed to execute script '__main__' due to unhandled exception!</code>

I am really no expert here but those lines from __init__ [820+] ...

<code>
        # create sub-directory for ad to download:</br>
        relative_directory = str(self.config['ad_files'][0]).split('**', maxsplit=1)[0]
</code>

... don't make sense to me with respect to ...

<code>
ad_files:
  - '**/ad_*.{json,yml,yaml}'</code>

... from config.yaml.

Otherwise everything works fine with a more or less plain vanilla configuration on Windows 10.
Sorry, but I was not able to get any proper formatting done for this post.

**Comment by Raketenphysik** [comment]
OK, so changing config did the trick

<code>
  - '/ads/**/ad_*.{json,yml,yaml}'
 </code>
<br><br>
BUT: Ads are downloaded to root folder - not to relative path - this way.

**Comment by baflo** [comment]
Thank you for the hint! I had the same problem and using you solution, I tried with relative paths. This works for me (just adding `./` to the beginning of the glob): 

```
ad_files:
  - './**/ad_*.{json,yml,yaml}'
```
