### ISSUE TITLE
Docker (Captcha present! Please solve and close the captcha, but DON'T click)

### ISSUE THREAD

**Issue by Tommamgo** [Second-Hand-Friends/kleinanzeigen-bot#138]
Unfortunately it is not possible to skip the captcha.

config: 
# browser configuration
browser:
  #https://peter.sh/experiments/chromium-command-line-switches/
  arguments:
    # https://stackoverflow.com/a/50725918/5116073
    - --disable-dev-shm-usage
    - --no-sandbox
    - --headless
    - --start-maximized
  binary_location: # path to custom browser executable, if not specified will be looked up on PATH
  extensions: [] # a list of .crx extension files to be loaded
  use_private_window: true
  user_data_dir: "" # see https://github.com/chromium/chromium/blob/main/docs/user_data_dir.md
  profile_name: ""

ERROR: 

[INFO] Logging to [/mnt/data/kleinanzeigen-bot.log]...
[INFO] App version: 0.1.dev180+geca782c.d20221112
[DEBUG] Loading [kleinanzeigen_bot.resources.config_defaults.yaml]...
[INFO] Loading config from [/mnt/data/config.yaml]...
[DEBUG] Loading categories from [kleinanzeigen_bot.resources.categories.yaml]...
[INFO]  -> found 138 categories
[INFO] Searching for ad config files...
[INFO]  -> found 1 ad config file
[DEBUG] Loading [kleinanzeigen_bot.resources.ad_fields.yaml]...
[INFO] Loading ad from [/mnt/data/my_ads/ad_buchse.yaml]...
[INFO] Loaded 1 ad
[INFO] Creating WebDriver session...
[INFO] Using pre-installed Chrome Driver [/usr/bin/chromedriver]
[INFO]  -> Custom chrome argument: --disable-dev-shm-usage
[INFO]  -> Custom chrome argument: --no-sandbox
[INFO]  -> Custom chrome argument: --headless
[INFO]  -> Custom chrome argument: --start-maximized
[DEBUG] Effective browser arguments: ['--incognito', '--disable-crash-reporter', '--no-first-run', '--no-service-autorun', '--disable-dev-shm-usage', '--no-sandbox', '--headless', '--start-maximized']
[DEBUG] Effective browser extensions: []
[DEBUG] Effective experimental options: {'excludeSwitches': ['enable-automation'], 'useAutomationExtension': False, 'prefs': {'credentials_enable_service': False, 'profile.password_manager_enabled': False, 'profile.default_content_setting_values.notifications': 2, 'devtools.preferences.currentDockState': '"bottom"'}}
[INFO] New WebDriver session is: xxxxx http://localhost:45921
[INFO] Logging in as [xx@xxx.xx]...
[DEBUG]  -> Opening [https://www.ebay-kleinanzeigen.de/m-einloggen.html?targetUrl=/]...
[INFO]  ... pausing for 2000 ms ...
[DEBUG]  ... pausing for 1406 ms ...
[DEBUG]  ... pausing for 1042 ms ...
[DEBUG]  ... pausing for 277 ms ...
[DEBUG]  ... pausing for 1216 ms ...
[WARNING] ############################################
[WARNING] # Captcha present! Please solve and close the captcha, but DON'T click 'Einloggen'.
[WARNING] ############################################

'''
[WARNING] ############################################
[WARNING] # Captcha present! Please solve and close the captcha, but DON'T click 'Einloggen'.
[WARNING] ############################################
'''

Is there any way to open the browser manually? 

Or are there any other possible solutions?

**Comment by sebthom** [comment]
You need to run an X11-Server on your host and set the X11_DISPLAY environment variable before your run the container. See https://github.com/Second-Hand-Friends/kleinanzeigen-bot#installation-from-source-using-docker
