### ISSUE TITLE
Download all does not work (for multiple pages)

### ISSUE THREAD

**Issue by provinzio** [Second-Hand-Friends/kleinanzeigen-bot#149]
The code crashes with an error when trying the get the pagination of the ad overview page. This boils down to the css selector name which seems to be dynamically changing. The current code does not work in multiple cases. 

#147

@PhilK-7

**Comment by PhilK-7** [comment]
I suspected the jsx number (probably coming from React) depends on the login session, but it doesn't. I'm still not sure that this number is completely dynamic. Either way, the class of the section element should not be used.

I will look into it.
