### ISSUE TITLE
Direkt kaufen and shipping_costs don't work together

### ISSUE THREAD

**Issue by tegger2000** [Second-Hand-Friends/kleinanzeigen-bot#155]
The activated "Direkt kaufen" and manual shipping don't work together. Is there an option to deactivate "Direkt kaufen" ?

**Comment by TheLexus** [comment]
Same for me... it always complains that  I need to select an delivery options (and dont set shipping costs by myself).

**Comment by inspirationally** [comment]
> The activated "Direkt kaufen" and manual shipping don't work together. Is there an option to deactivate "Direkt kaufen" ?

You can deactivate in the single ads files with adding the line

`sell_directly: false
`

**Comment by TheLexus** [comment]
Don’t work always. The default is false but of that option at the website is enabled (it seems to be enabled by default) it will not be deactivated activly. If you deactivate it at the browser window manually it stays deactivated as long as that browser window (incognito mode) is used.

**Comment by DreckSoft** [comment]
Same here. "Direkt kaufen" seems to be enabled by default for some (!) categories if you offer shipping. It will not be disabled by the script regardless of the configuration.

**Comment by DreckSoft** [comment]
Actually it also doesn't work without shipping_costs. If  "Direkt kaufen" is activated posting an add ALWAYS fails. It seems to be dependent on the account if that is the case. However it is also activated if it has never been used and is not configured. For me it also does NOT stay deactivated for the session if deactivated manually once.
