### ISSUE TITLE
NoSuchElementException: Message: Element id='postad-step1-sbmt' not found

### ISSUE THREAD

**Issue by Code-Red-666** [Second-Hand-Friends/kleinanzeigen-bot#159]
It seeems something has changed on the website. Is anybody able to help out with this? This error has started to appear about 2-3 days ago. Before that time everything went well. Im using the current version, I just downloaded it.

**Comment by quadratmuede** [comment]
I can confirm this. It is not working anymore with the error "NoSuchElementException: Message: Element id='postad-step1-sbmt' not found".
