### ISSUE TITLE
Importer / Converter for the "old" ebayKleinanzeigen script 

### ISSUE THREAD

**Issue by DreckSoft** [Second-Hand-Friends/kleinanzeigen-bot#16]
An importer / converter for the JSON file of the ebayKleinanzeigen script would be very helpful so that we don't have to start with zero again. The one time options are fine, it's likely faster to do it manually but converting the ads in the JSON to the new format would safe a lot of time.

**Comment by sebthom** [comment]
I think that is a nice idea and could be easily implemented in bash using a tool like https://github.com/mikefarah/yq

contributions are welcome

**Comment by sebthom** [comment]
I don't think this is relevant anymore, closing the issue.
