### ISSUE TITLE
problem with condition

### ISSUE THREAD

**Issue by tegger2000** [Second-Hand-Friends/kleinanzeigen-bot#168]
For the condition there is no dropdown anymore, but a popup window appears with the options and explanatory texts.
<div class="jsx-1033793466 SelectionButton--Left">
<span class="jsx-3300347113">Neu</span>
</div>
How can include this in the specials or is this new and unsupported ?

**Comment by DreckSoft** [comment]
It's currently not supported. My error message:
NoSuchElementException: Message: Failed to set special attribute [kleidung_herren.condition_s]

category: 153/160/shirts
