### ISSUE TITLE
[Bug] Cannot publish currently - big change(s) on and before 16.5.2023 @ Kleinanzeigen?

### ISSUE THREAD

**Issue by svensvond** [Second-Hand-Friends/kleinanzeigen-bot#180]
Cannot publish any add since about 2 weeks.

![image](https://github.com/Second-Hand-Friends/kleinanzeigen-bot/assets/37634123/1b40bd92-8c67-44c5-8ab7-7f085972b497)

**Comment by dojo90** [comment]
duplicate of https://github.com/Second-Hand-Friends/kleinanzeigen-bot/issues/176
