### ISSUE TITLE
Starting Chromium with specific profile does not work

### ISSUE THREAD

**Issue by Nuc1eoN** [Second-Hand-Friends/kleinanzeigen-bot#192]
I have tried to use a dedicated chromium profile for the bot. Therefore I have specified:

```yml
browser:
  profile_name: 'bot'
```
According to the start up logs this setting is being applied:

```
[INFO]  -> Browser Profile Name: bot
```

However Chormium will start with the default profile. For some reason also, from within that Chromium window it is not possible to access other profiles apart from Guest (they are not being displayed).

I have also tried additionally setting 'user_data_dir' but got the same results.

As another workaround I have tried adding the following as a startup argument: `--profile-directory="Profile 1"` (see https://superuser.com/a/377195). However same results. Manually running `chromium --profile-directory="Profile 1"` in my terminal works though.

There must be something in the way that kleinanzeigen-bot executes chromium, that prevents profiles from being used.

Chromium v114.0.5735.133

**Comment by ghoeffner** [comment]
Confirmed.
```
[INFO] Using Browser: GOOGLE-CHROME 116.0.5845.96 [C:\Program Files (x86)\Google\Chrome\Application\chrome.exe]
[ERROR] ValueError: There is no such driver by url https://chromedriver.storage.googleapis.com/LATEST_RELEASE_116
[1808] Failed to execute script '__main__' due to unhandled exception!
```

**Comment by ghoeffner** [comment]
Fixed in latest.
