### ISSUE TITLE
Sell directly slider not switching

### ISSUE THREAD

**Issue by xNoir1990** [Second-Hand-Friends/kleinanzeigen-bot#194]
Sell directly slider is on by default and won't turn off even if set to false.

You have to change __init__.py line #518 and #520 from:
self.web_click(By.XPATH, '//*[contains(@class, "BuyNowSection")]//span[contains(@class, "Toggle--Slider")]')

to:
self.web_click(By.XPATH, '//*[contains(@class, "BuyNowSection")]//div[contains(@class, "Toggle--Slider")]')

Greeting,
xNoir1990

**Comment by DreckSoft** [comment]
Works with the change. Thanks.
