### ISSUE TITLE
New Webdailogs - publishing fails

### ISSUE THREAD

**Issue by svensvond** [Second-Hand-Friends/kleinanzeigen-bot#196]
New Dialog popups: "Zustand".
If not selecting manually, publishing fails.

**Comment by dragonheart100** [comment]
I have the same problem.

This does not solve the problem.
special_attributes:
  [category].condition_s: like_new

**Comment by IchSkill** [comment]
any progress on this?

**Comment by DreckSoft** [comment]
I think the issue was that selecting shipping options actually popped up the condition dialog. That should have been fixed with #218 

Usually condition is optional and if needed you can select it with 
[category].condition_s: <condition>
