### ISSUE TITLE
Precompiled exe missing from last release

### ISSUE THREAD

**Issue by johannesschweig** [Second-Hand-Friends/kleinanzeigen-bot#198]
@sebthom There is no precompiled exe in the last release (d2f3ad4).

**Comment by johannesschweig** [comment]
There are no releases for me. 
Also `curl -L https://github.com/Second-Hand-Friends/kleinanzeigen-bot/releases/download/latest/kleinanzeigen-bot-linux-amd64 -o kleinanzeigen-bot` returns a Not Found for me.
![image](https://github.com/Second-Hand-Friends/kleinanzeigen-bot/assets/10641030/f76fc8b5-b1af-4846-b675-429ad1d9d557)

**Comment by sebthom** [comment]
Interesting, looks like the build job didn't publish the release but kept it as draft for some reason. I now manually published it.
