### ISSUE TITLE
ValueError: There is no such driver by url […] LATEST_RELEASE_116

### ISSUE THREAD

**Issue by myhd** [Second-Hand-Friends/kleinanzeigen-bot#204]
I'd LOVE to test this nifty app, but alas…
What can I do to resolve this?

MacOS 13.5.1
Version 116.0.5845.140 (Offizieller Build) (arm64)

Using the MacOS binary on M2 Chip.
First launch cant get past this error message:

`xxx@xxx kleinanzeigen % ./kleinanzeigen-bot download`

```
[INFO] Logging to [/Users/xxx/kleinanzeigen/kleinanzeigen-bot.log]...
[INFO] App version: 0.1.dev1+g51ef9c8
[WARNING] You provided no ads selector. Defaulting to "new".
[INFO] Loading config from [/Users/xxx/kleinanzeigen/config.yaml]...
[INFO]  -> found 145 categories
[INFO] Creating WebDriver session...
[INFO] Using Browser: GOOGLE-CHROME 116.0.5845 [/Applications/Google Chrome.app/Contents/MacOS/Google Chrome]
[ERROR] ValueError: There is no such driver by url https://chromedriver.storage.googleapis.com/LATEST_RELEASE_116
[40991] Failed to execute script '__main__' due to unhandled exception!
```

**Comment by Piranha1511** [comment]
+1 
Same issue on my side

**Comment by ilyaZar** [comment]
Same issue on a linux machine 

Platform:
```bash
Linux Mint 21.1 x86_64
```

Error message:
```bash
[INFO] Using Browser: GOOGLE-CHROME 116.0.5845 [/usr/bin/google-chrome]
[ERROR] ValueError: There is no such driver by url https://chromedriver.storage.googleapis.com/LATEST_RELEASE_116
```

**Comment by jniggemann** [comment]
https://chromedriver.chromium.org/downloads

> If you are using Chrome version 115 or newer, please consult[ the Chrome for Testing availability dashboard](https://googlechromelabs.github.io/chrome-for-testing/). This page provides convenient [JSON endpoints](https://googlechromelabs.github.io/chrome-for-testing/known-good-versions-with-downloads.json) for specific ChromeDriver version downloading.

**Comment by sebthom** [comment]
Please try the latest release.

**Comment by jniggemann** [comment]
Confirm latest is working on Win 10 21H2 64bit.

**Comment by myhd** [comment]
> Please try the latest release.

Thanks! Under 13.5.2 (22G91) MacOS Ventura, creating a web driver session now works: A Chrome window comes up.

From there, I can't get to log in, but I might write another issue on that.

**Comment by sebthom** [comment]
Thanks for the feedback.

**Comment by ilyaZar** [comment]
Sorry for the delay, but just as a note on a linux mint system: 

```bash
google-chrome-stable --version
Google Chrome 117.0.5938.149
```

works
