### ISSUE TITLE
SSL: CERTIFICATE_VERIFY_FAILED

### ISSUE THREAD

**Issue by juvev** [Second-Hand-Friends/kleinanzeigen-bot#207]
I'm trying to download ads, but getting this error msg:
`[ERROR] URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1002)>
[167650] Failed to execute script '__main__' due to unhandled exception!
`
Any idea how to fix this?! Thanks.

**Comment by JigaoLuo** [comment]
Same Issue:
```
WARNING] ############################################
[WARNING] # Captcha present! Please solve and close the captcha, but DON'T click 'Einloggen'.
[WARNING] ############################################
[INFO] Scanning your ad overview...
[INFO]  ... pausing for 2294 ms ...
[INFO]  ... pausing for 2911 ms ...
It seems like all your ads fit on one overview page.
[INFO] 7 ads were found!
[INFO] Start fetch task for all your ads!
(no popup)
[INFO] Deleting current folder of ad...
[INFO] New directory for ad created at downloaded-ads/ad_2567680612.
[INFO] Extracting information from ad with title "SACHE"
[INFO] Found 2 images.
[ERROR] URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)>
[421716] Failed to execute script '__main__' due to unhandled exception!
```

**Comment by sebthom** [comment]
Can you please try the latest release which is based on Python 3.12. Also, what operating system are you using?

**Comment by denishartl** [comment]
I am also facing the same issue. Tested on the latest version currently available without building myself (https://github.com/Second-Hand-Friends/kleinanzeigen-bot/releases/download/latest/kleinanzeigen-bot-darwin-amd64).

I am using MacOS Sonoma (14.0, Build 23A344)

**Comment by JigaoLuo** [comment]
> Can you please try the latest release which is based on Python 3.12. Also, what operating system are you using?

Do I have to install the Python 3.12?

**Comment by sebthom** [comment]
> > Can you please try the latest release which is based on Python 3.12. Also, what operating system are you using?
> 
> Do I have to install the Python 3.12?

No, it is bundled.

**Comment by sebthom** [comment]
> I am also facing the same issue. Tested on the latest version currently available without building myself ([`latest` kleinanzeigen-bot-darwin-amd64 (download)](https://github.com/Second-Hand-Friends/kleinanzeigen-bot/releases/download/latest/kleinanzeigen-bot-darwin-amd64)).
> 
> I am using MacOS Sonoma (14.0, Build 23A344)

I think this is a MacOS specific issue like this https://github.com/pyinstaller/pyinstaller/issues/7229

I don't have a Mac so I can neither reproduce it nor have an idea how to fix it.

**Comment by denishartl** [comment]
I can confirm that it seems to be a MacOS issue only. Works fine on Windows for me.

**Comment by sebthom** [comment]
Does this issue still exist with the latest release?

**Comment by fellnerse** [comment]
I just ran the latest release and faced this issue. Awesome project btw!

**Comment by mhmuc1** [comment]
This must be opened again.

[INFO] Extracting information from ad with title "Spiegel silber"
[INFO] Found 1 images.
[ERROR] URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1000)>

Latest version of today on docker windows
