### ISSUE TITLE
Chrome does not start, when a profil is used

### ISSUE THREAD

**Issue by VWthefirst** [Second-Hand-Friends/kleinanzeigen-bot#209]
Hi, 
I do have a little problem. When I do not define a Profil everything works great. But of course I have to solve the captch by hand. Therefore I like to load Chrome with my existing Profile, because I'am already logged in there. Now when I insert user_data_dir: 'C:\Users\XXX\AppData\Local\Google\Chrome\User Data' and profile_name: 'C:\Users\XXX\AppData\Local\Google\Chrome\User Data\Profile 1' Chrome failed to start and I get the Error: Devtoolsactiveport file doesn't exist.

What am I doing wrong? Please help.

Thanks in advance!
VW

**Comment by sebthom** [comment]
I cannot reproduce this. Works fine for me. Please try with the latest release.

**Comment by DreckSoft** [comment]
profile_name must be "Profile 1" not the entire path!
