### ISSUE TITLE
How to use 3rd-level category?

### ISSUE THREAD

**Issue by jniggemann** [Second-Hand-Friends/kleinanzeigen-bot#21]
Sometimes a third-level category is required, how do I use it in an ad?
Example: In  "Auto, Rad & Boot > Autoteile & Reifen"  I'd like to use "Weitere Autoteile", which is selected in the art_s-dropdown.

**Comment by sebthom** [comment]
I cannot try it myself atm. I am abroad and being geo-blocked, How did you specify it in the ebayKleinanzeigen app?

**Comment by jniggemann** [comment]
I specified it via "[additional_category_options](https://github.com/Second-Hand-Friends/ebayKleinanzeigen/blob/65da809deebd7609cb39f318343ce7cda4bf0f2e/config.json.example#L36)".

**Comment by sebthom** [comment]
@jniggemann can you not use this path `210/223/sonstige_autoteile` as category?
