### ISSUE TITLE
Add easy multi-path in `config.yaml` via `ad_files`

### ISSUE THREAD

**Issue by ilyaZar** [Second-Hand-Friends/kleinanzeigen-bot#212]
Does the top level field `ad_files` support a way of specifying multiple paths quickly and easily (perhaps only giving individual dirs)? 

Meaning currently the start of `config.yaml` looks like

```bash
# wild card patterns to select ad configuration files
# if relative paths are specified, then they are relative to this configuration file
ad_files:
  - "path/to/top-level/that/is/very/lengthy/item-01/ad.yaml"
  - "path/to/top-level/that/is/very/lengthy/item-02/ad.yaml"
  - "path/to/top-level/that/is/very/lengthy/item-03/ad.yaml"
...
```

But because path names are lengthy I want something like

```bash
ad_files:
  - path="path/to/top-level/that/is/very/lengthy"
  - "path/item-01/ad.yaml"
  - "path/item-02/ad.yaml"
  - "path/item-03/ad.yaml"
 ...
```

Or something similar where I can quickly exchange `item-01` through `item-03` whenever something is sold etc.

Notably, the last bit `ad.yaml` is also repetitive which could suggest to use further path level concatenation tricks....

**Comment by sebthom** [comment]
You currently have these options:
1. move the config.yaml closer to the add files and then reference the ad files relatively, e.g. move config.yaml to `path/to/top-level/that/is/very/lengthy/config.yaml` and use:
    ```yaml
	ad_files:
	  - "./path/item-01/ad.yaml"
	  - "./path/item-02/ad.yaml"
	  - "./path/item-03/ad.yaml"
	 ...
    ```
1. use [wildcards](https://facelessuser.github.io/wcmatch/wcmatch/#globstar):
    ```yaml
	ad_files:
	  - "path/to/top-level/that/is/very/lengthy/path/item-*/ad.yaml"
	 ...
    ````
1. use [braces expansion](https://facelessuser.github.io/wcmatch/wcmatch/#brace):
    ```yaml
	ad_files:
	  - "path/to/top-level/that/is/very/lengthy/path/item-{01,02,03}/ad.yaml"
	 ...
    ````
