### ISSUE TITLE
New anti-bot "feature"

### ISSUE THREAD

**Issue by DreckSoft** [Second-Hand-Friends/kleinanzeigen-bot#219]
Kleinanzeigen gets more annoying every month. Now with chrome I get an additional verification request before the login appears.

![Screenshot_20231020_180813](https://github.com/Second-Hand-Friends/kleinanzeigen-bot/assets/68750712/12ffa31f-8cbc-4302-8415-ce7108d2b1ec)

Unfortunately even if I solve it in time before the script exits, I only get "Du wurdest gesperrt" ("You have been locked out"). 

Sometimes after a few restarts, the puzzle won't appear but it gets more rare. Strangely I've never seen this in Firefox and it can be solved in a regular chromium browser.

**Comment by ghoeffner** [comment]
Getting this too, seems related to a new type of login form.

**Comment by sebthom** [comment]
We may have to look into using https://pypi.org/project/undetected-chromedriver/

**Comment by DreckSoft** [comment]
A workaround is to create a profile in Chromium per Kleinanzeigen account and use that in a non-private window. Then you only have to login once. It's more convenient anyways, saves the captcha at the beginning.

**Comment by ilyaZar** [comment]
@DreckSoft Would you mind giving a bit more details as a preliminary workaround for this ? I get blogged to an extent that it almost always ends up on this page, sometimes after a few restarts worked before but now it seems not to work at all (at least for me) ....

**Comment by apeltzer** [comment]
> A workaround is to create a profile in Chromium per Kleinanzeigen account and use that in a non-private window. Then you only have to login once. It's more convenient anyways, saves the captcha at the beginning.

Couldnt get this to work myself either. It always takes the default profile, even when setting the entry to `false` and the profile path properly.

**Comment by jonmert** [comment]
I'm experiencing the same problem. Even after completing the captcha manually I am getting blocked.

**Comment by DreckSoft** [comment]
Launching chromedriver with the correct profile works for me but I'm no longer logged in. If I start Chromium with that profile I am. So really strange.

**Comment by DreckSoft** [comment]
It seems it is getting worse. When I start Chromium, everything works and I'm logged in. With Chromedriver I currently ALWAYS getting the anti-bot thing. So no publishing possible at all.

**Comment by DreckSoft** [comment]
> We may have to look into using https://pypi.org/project/undetected-chromedriver/

That seems to require more adjustments than just importing undetected_chromedriver :(

**Comment by mcsurfi** [comment]
The problem still exists....

**Comment by DreckSoft** [comment]
The following works at least with my patch (haven't tried without):
- You MUST have a working setup to use an existing Chromium profile. See instructions on the main page.
- Open Chromium manually and log in. 
- Go to your ads page
- Close Chromium
- Start the app. It will go to the login page and submit user/pw but will immediately go back to the login page. 
- When that is the case enter https://kleinanzeigen.de into the address bar (better have that copied to the clipboard before and just paste)
- If the timing was right (!), it will detect that you are already logged in. If not, try again.

**Comment by DreckSoft** [comment]
My current version fixed the login check. So you just need a working Chromium profile and need to be logged in. 

I can't do another pull request as I haven't synced to the latest changes with the dependencies update. 

https://github.com/DreckSoft/kleinanzeigen-bot

No binaries are provided you will have to use the source code version with pdm.

**Comment by elgarfo** [comment]
as i was unable to find clear instructions on what "working profile" meant and i suspect others to feel the same: this is the way i got it to work.

⚠️: i am using docker on debian 12 in wsl2 on windows with vcxsrv as my display server. YMMV. that being said, i can imagine this is universally working for the docker-version.

## setup config

as mentioned above, i modified the chromium options in `config.yaml`:

```yaml
browser:
...
  use_private_window: false
  user_data_dir: '/mnt/data/userdata'
  profile_name: 'profile'
```

this provides a persistent storage for the docker-based chromium. i chose /mnt/data/userdir as that was already mounted as a volume in the example commands.

## prepare persistent profile

to prepare the profile. you need to login manually to your kleinanzeigen.de account. as the bot gives very little time and often triggers the captcha and blocked message, i recommend manually running chromium for the first login. this will open a chromium instance with the configured persistent profile data. just surf to https://kleinanzeigen.de/, manually login and close the browser afterwards.

```bash
docker run --rm -it --shm-size=256m \
  -e DISPLAY=$X11_DISPLAY \
  -v ${PWD}:/mnt/data \
  --entrypoint /usr/bin/chromium \
  ghcr.io/second-hand-friends/kleinanzeigen-bot \
  --user-data-dir=/mnt/data/userdata/ \
  --profile-directory=profile \
  --disable-crash-reporter \
  --no-first-run \
  --no-service-autorun \
  --no-sandbox
```

thats it. your profile is now holding session-data for your kleinanzeigen.de account and will work with commands like `docker run --rm -it --shm-size=256m -e DISPLAY=$X11_DISPLAY -v ${PWD}:/mnt/data ghcr.io/second-hand-friends/kleinanzeigen-bot download` to download all your ads.

## using multiple accounts

if you want to use multiple kleinanzeigen.de accounts, you can repeat the preparation step for each individual account and just change the `--profile-directory` parameter together with a matching `config.yaml`

## 

i did not use DreckSofts fixed version with the undetected-chromedriver, as i did not want to build from source. hopefully the login-fix gets eventually merged. as of now i'm fine with this workaround.

**Comment by ilyaZar** [comment]
@elgarfo this explanation is perfect thanks, I also struggled with the notion of "chrome profile" and a more elaborated explanation for the workaround greatly helps 👍

**Comment by RomanRadkoMobile** [comment]
Hi guys,
Dose somebody faced this "Chromium has locked the profile issue..." ?
![image](https://github.com/Second-Hand-Friends/kleinanzeigen-bot/assets/148379609/da4a2537-b1ca-4d4e-bb4c-ae301103135c)

**Comment by DenisLanz** [comment]
After wasting couple of hours trying to get @elgarfo 's solution with docker to work on macOS with Docker and XQuartz I gave up… just to figure out a way easier solution to use an existing profile and it's sessions on macOS.

Start chrome with the remote debugging port mapped to 9222 in one terminal session:

```
/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --remote-debugging-port=9222
```

Log In to eBay Kleinanzeigen and keep the Window Open.

and execute kleinanzeigen-bot through pdm `pdm run app publish --config=<config file>` in another terminal session with the following settings:

```
browser:
  arguments:
    - --disable-dev-shm-usage
    - --no-sandbox
    - --remote-debugging-port=9222
  binary_location: "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome"
  use_private_window: false
  user_data_dir: '~/Library/Application Support/Google/Chrome'
  profile_name: 'Default'
  ```
  
It might be necessary to change the `~` to the absolute path to the User Profile - just changed it for the sake of sharing it here.

**Comment by lamyergeier** [comment]
@DenisLanz  I modified your instructions for Linux, but I was unsuccessful in skipping the issue posted by the OP.

**Comment by DenisLanz** [comment]
Try adding `- --profile-directory='Default'`to the selenium arguments. I had this in but wasn't sure if it is the same as the Kleinanzeigen bot `profile_name` settings. Published all my ads for now so I couldn't test if it's necessary or not. The timeout error from you other issue indicates, that the profile is not loaded correctly and you're not reusing the exisiting session. If you don't see an `[INFO] Already logged in as [<username>]. Skipping login.` in the pdm log and the ads are created in the same window you're logged in before there is an issue with the profile.

**Comment by TylonHH** [comment]
> Try adding

you mean like this?
```browser:
  # https://peter.sh/experiments/chromium-command-line-switches/
  arguments:
    # https://stackoverflow.com/a/50725918/5116073
    - --disable-dev-shm-usage
    - --no-sandbox
    - --profile-directory='Default'
    # --headless
    # --start-maximized
  binary_location: 'C:\Program Files\Google\Chrome\Application\chrome.exe' # path to custom browser executable, if not specified will be looked up on PATH
  extensions: [] # a list of .crx extension files to be loaded
  use_private_window: false
  user_data_dir: '' # see https://github.com/chromium/chromium/blob/main/docs/user_data_dir.md
  profile_name: ''
```

**Comment by TylonHH** [comment]
> this

I get this with this config. It still generate a new session:
```
2024-01-15 15:29:45,277 [INFO] App version: 2024+8389123
2024-01-15 15:29:45,277 [INFO] Python version: 3.12.1 (tags/v3.12.1:2305ca5, Dec  7 2023, 22:03:25) [MSC v.1937 64 bit (AMD64)]
2024-01-15 15:29:45,278 [WARNING] You provided no ads selector. Defaulting to "new".
2024-01-15 15:29:45,287 [INFO] Loading config from [C:\TEMP\kleinanzeigen-bot\config.yaml]...
2024-01-15 15:29:45,328 [INFO]  -> found 145 categories
2024-01-15 15:29:45,329 [INFO] Creating WebDriver session...
2024-01-15 15:29:45,367 [INFO] Using Browser: GOOGLE-CHROME 120.0.6099.217 [C:\Program Files\Google\Chrome\Application\chrome.exe]
2024-01-15 15:29:47,130 [INFO]  -> Browser User Data Dir: C:\Users\Rene\AppData\Local\Google\Chrome\User Data\Default
2024-01-15 15:29:47,131 [INFO]  -> Browser Profile Name: Default
2024-01-15 15:29:47,132 [INFO]  -> Custom chrome argument: --disable-dev-shm-usage
2024-01-15 15:29:47,133 [INFO]  -> Custom chrome argument: --no-sandbox
2024-01-15 15:29:47,133 [INFO]  -> Custom chrome argument: --profile-directory='Default'
2024-01-15 15:29:47,133 [INFO]  -> Chrome binary location: C:\Program Files\Google\Chrome\Application\chrome.exe
2024-01-15 15:29:48,494 [INFO] New WebDriver session is: 8716a3ba62a0f315f5840277df7b1dcf http://localhost:62614
2024-01-15 15:29:48,495 [INFO] Checking if already logged in
2024-01-15 15:29:49,874 [INFO]  ... pausing for 2000 ms ...
2024-01-15 15:29:56,978 [INFO] Logging in as [tylonhh............
```

**Comment by DenisLanz** [comment]
You need to check how you can run chrome with the remote debugging port enabled (e.g.9222) on windows and add the 
`- --remote-debugging-port=9222` setting to the config. Without it you can't use the existing session.

**Comment by DenisLanz** [comment]
Tested it again. Running Chrome with the remote debugging Port in one terminal session:
```
/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --remote-debugging-port=9222
```
Logging into Kleinanzeigen keeping the chrome window open. And running kleinanzeigen bot through pdm with the follwing settings in another termianl works well on macOS:

```
browser:
  arguments:
    - --disable-dev-shm-usage
    - --no-sandbox
    - --remote-debugging-port=9222
    - --profile-directory='Default'
  binary_location: "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome"
  use_private_window: false
  user_data_dir: '~/Library/Application Support/Google/Chrome'
  profile_name: 'Default'
  ```
  
there will be a new empty chrome window but the ads will be published in the previously opened chrome window in the background so make sure to look at that.

**Comment by TylonHH** [comment]
As I'm on a Windows maschine I run in a command line `C:\Program Files\Google\Chrome\Application\chrome.exe --disable-dev-shm-usage --no-sandbox --profile-directory='Default' --remote-debugging-port=9222`
I hoped that is the command wich the bot runs also. There was a strange Chrome. The default profile was not loaded. There was a new profile. Anyways, I logged in to kleinanzeigen and kept chrome open. Then I run `kleinanzeigen-bot download`
I new chrome opened and tried to login, captcha prompted and said I got blocked. The other windows in the background did nothing, and there was no download.

**Comment by TylonHH** [comment]
Without Sandbox and already open chrome windows
```
2024-01-16 00:23:11,055 [INFO] App version: 2024+8389123
2024-01-16 00:23:11,055 [INFO] Python version: 3.12.1 (tags/v3.12.1:2305ca5, Dec  7 2023, 22:03:25) [MSC v.1937 64 bit (AMD64)]
2024-01-16 00:23:11,064 [INFO] Loading config from [C:\TEMP\kleinanzeigen-bot\config.yaml]...
2024-01-16 00:23:11,103 [INFO]  -> found 145 categories
2024-01-16 00:23:11,103 [INFO] Creating WebDriver session...
2024-01-16 00:23:11,138 [INFO] Using Browser: GOOGLE-CHROME 120.0.6099.217 [C:\Program Files\Google\Chrome\Application\chrome.exe]
2024-01-16 00:23:12,786 [INFO]  -> Browser Profile Name: Default
2024-01-16 00:23:12,786 [INFO]  -> Custom chrome argument: --disable-dev-shm-usage
2024-01-16 00:23:12,788 [INFO]  -> Custom chrome argument: --profile-directory='Default'
2024-01-16 00:23:12,788 [INFO]  -> Custom chrome argument: --remote-debugging-port=9222
2024-01-16 00:23:12,788 [INFO]  -> Chrome binary location: C:\Program Files\Google\Chrome\Application\chrome.exe
2024-01-16 00:23:16,071 [ERROR] WebDriverException: Message: disconnected: unable to connect to renderer
Stacktrace:
	GetHandleVerifier [0x00BF6EE3+174339]
	(No symbol) [0x00B20A51]
	(No symbol) [0x00836FF6]
	(No symbol) [0x0085E500]
	(No symbol) [0x0085B9D0]
	(No symbol) [0x00857A0F]
	(No symbol) [0x0088E259]
	(No symbol) [0x0088DBBA]
	(No symbol) [0x00886DA6]
	(No symbol) [0x00861034]
	(No symbol) [0x00861F8D]
	GetHandleVerifier [0x00C94B1C+820540]
	sqlite3_dbdata_init [0x00D553EE+653550]
	sqlite3_dbdata_init [0x00D54E09+652041]
	sqlite3_dbdata_init [0x00D497CC+605388]
	sqlite3_dbdata_init [0x00D55D9B+656027]
	(No symbol) [0x00B2FE6C]
	(No symbol) [0x00B283B8]
	(No symbol) [0x00B284DD]
	(No symbol) [0x00B15818]
	BaseThreadInitThunk [0x7655FCC9+25]
	RtlGetAppContainerNamedObjectPath [0x77447C6E+286]
	RtlGetAppContainerNamedObjectPath [0x77447C3E+238]
```

**Comment by DenisLanz** [comment]
You probably just need: 
```
C:\Program Files\Google\Chrome\Application\chrome.exe --remote-debugging-port=9222
```

to start chrome with the remote debugging port open.

The rest of the flags are for  the config only. `--remote-debugging-port=9222` has a sending and a receiving end. 

Thats as far as I can help you on windows, there might also be other issues you need to be able to debug yourself.

**Comment by TylonHH** [comment]
ok so I tested it also with edge. the behavior is the same. As far as I see: it seems that the browser wich the bot starts is a clean browser without any cookie or cache, with esdge and chrome.
In chrome I dont see any profile (top right). It looks like the browser is running as an admin or different OS user with its own cache etc. Is maybe something knwon in this direction, how the browser is startet, for eg with wich user?!?

**Comment by DenisLanz** [comment]
You're using the pdm build, not docker nor packaged version, right? Please post your config.yml as well as the commands you use to open chrome and to start pdm. Not sure if I can support as I'm not familiar with how a terminal application behaves with windows.

**Comment by TylonHH** [comment]
> You're using the pdm build, 
I use the latest [kleinanzeigen-bot-windows-amd64.exe ](https://github.com/Second-Hand-Friends/kleinanzeigen-bot/releases/tag/latest). No docker.

**config.yml**
```
ad_files:
  - ./**/ad_*.{json,yml,yaml}

# default values for ads, can be overwritten in each ad configuration file
ad_defaults:
  active: true
  type: OFFER # one of: OFFER, WANTED
  description:
    prefix: ''
    suffix: ''
  price_type: NEGOTIABLE # one of: FIXED, NEGOTIABLE, GIVE_AWAY, NOT_APPLICABLE
  shipping_type: SHIPPING # one of: PICKUP, SHIPPING, NOT_APPLICABLE
  sell_directly: false # requires shipping_options to take effect
  contact:
    name: ''
    street: ''
    zipcode:
    phone: '' # IMPORTANT: surround phone number with quotes to prevent removal of leading zeros
  republication_interval: 7 # every X days ads should be re-published

# additional name to category ID mappings, see default list at
# https://github.com/Second-Hand-Friends/kleinanzeigen-bot/blob/main/kleinanzeigen_bot/resources/categories.yaml
# Notebooks: 161/278 # Elektronik > Notebooks
# Autoteile: 210/223/sonstige_autoteile # Auto, Rad & Boot > Autoteile & Reifen > Weitere Autoteile
categories: []

# browser configuration
browser:
  # https://peter.sh/experiments/chromium-command-line-switches/
  arguments:
    # https://stackoverflow.com/a/50725918/5116073
    #- --disable-dev-shm-usage
    #- --no-sandbox
    - --profile-directory='Default'
    - --remote-debugging-port=9222
    # --headless
    # --start-maximized
  binary_location: 'C:\Program Files\Google\Chrome\Application\chrome.exe' # path to custom browser executable, if not specified will be looked up on PATH
  extensions: [] # a list of .crx extension files to be loaded
  use_private_window: false
  user_data_dir: '' #'C:\Users\Rene\AppData\Local\Google\Chrome\User Data\Default' # see https://github.com/chromium/chromium/blob/main/docs/user_data_dir.md
  profile_name: 'Default'

# login credentials
login:
  username: 'tylonhh+ebayXXXXXXX.com'
  password: 'U8XXXXXXXXXYf'

I run cmd to start a terminal
navigate to the folder where the kleinanzeigen-bot.exe is saved and run `kleinanzeigen-bot --ads=all download`

**Comment by DenisLanz** [comment]
@TylonHH  where do you specify the config `--config`?  `kleinanzeigen-bot --ads=all downloads` or is it all in the same folder and it defaults?

**Comment by TylonHH** [comment]
@DenisLanz all default and within the same folder

**Comment by DenisLanz** [comment]
No idea… work well on a mac using building it with pdm just republished all my ads, you could try to use the pdm version yourself and not the pre-build version.

**Comment by HulkHoganNWO** [comment]
> still nothing seems to work for me using windows. tried it with both Edge and chrome and logged in browsers open and closed. Did anyone get it to work ?

Same problem here... Is there any hope for a fix/workaround for windows?

**Comment by knipknap** [comment]
The recent comment thread here makes it appear as though this problem only persists on Windows, but I have the same issue in Ubuntu still (no Docker, just using the script), and I can't get the script to re-use the existing session.

```
browser:
  arguments:
    - --disable-dev-shm-usage
    - --no-sandbox
    #- --remote-debugging-port=9222
  binary_location: /usr/bin/google-chrome
  extensions: [] # a list of .crx extension files to be loaded
  use_private_window: false
  user_data_dir: '/home/me/.config/google-chrome'
  profile_name: 'Profile 1'
```

Is this supposed to work? I also tried with `--remote-debugging-location=9222`, with no change, and also with `private_window=true`

**Comment by HulkHoganNWO** [comment]
Tried it at Ubuntu too, but with no luck (I am a beginner...). 
Is macOS the only OS, at which the script now works? Is there a chance, that it can be fixed by someone? It's frustrating at the moment :(

**Comment by kahironimashte** [comment]
> and execute kleinanzeigen-bot through pdm `pdm run app publish --config=<config file>` in another terminal session with the following settings:
> 
> ```
> browser:
>   arguments:
>     - --disable-dev-shm-usage
>     - --no-sandbox
>     - --remote-debugging-port=9222
>   binary_location: "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome"
>   use_private_window: false
>   user_data_dir: '~/Library/Application Support/Google/Chrome'
>   profile_name: 'Default'
> ```
> 
> It might be necessary to change the `~` to the absolute path to the User Profile - just changed it for the sake of sharing it here.

I tried this on Ubuntu 22.04 with the following settings and it **did not** work, maybe I configured something wrong: 

```
# browser configuration
browser:
  arguments:
    - --disable-dev-shm-usage
    - --no-sandbox
    - --remote-debugging-port=9222
  binary_location: /usr/bin chromium 
  extensions: [] 
  use_private_window: false
  user_data_dir: '~/.config/chromium' # see https://github.com/chromium/chromium/blob/main/docs/user_data_dir.md
  profile_name: 'Default'
```

**Comment by kahironimashte** [comment]
> > We may have to look into using https://pypi.org/project/undetected-chromedriver/
> 
> That seems to require more adjustments than just importing undetected_chromedriver :(

As a layman asking: what additional adjustments would we need to make for undetectet_coromedriver to work with kleinanzeigen-bot?

**Comment by HulkHoganNWO** [comment]
Well, I for me the kleinanzeigen-bot is dead until there is a real workaround or update for windows/linux....
Is someone using the kleinanzeigen-bot with linux/windows right now? Or only one person with mac?
Are there any alternative programs?

**Comment by rockodd** [comment]
> Well, I for me the kleinanzeigen-bot is dead until there is a real workaround or update for windows/linux.... Is someone using the kleinanzeigen-bot with linux/windows right now? Or only one person with mac? Are there any alternative programs?

For me is working on windows with the workaround from @DreckSoft

**Comment by HulkHoganNWO** [comment]
> > Well, I for me the kleinanzeigen-bot is dead until there is a real workaround or update for windows/linux.... Is someone using the kleinanzeigen-bot with linux/windows right now? Or only one person with mac? Are there any alternative programs?
> 
> For me is working on windows with the workaround from @DreckSoft

Thank you for your reply. That gives me hope.

Could you please, please give me some more details?
How do you installed the "kleinanzeigen-bot" on windows? With this command? -> "curl -L https://github.com/Second-Hand-Friends/kleinanzeigen-bot/releases/download/latest/kleinanzeigen-bot-windows-amd64.exe -o kleinanzeigen-bot.exe"

Which browser? Chrome or Edge?

I don't understand the following from "drecksoft": "No binaries are provided you will have to use the source code version with pdm."
How do I do that on windows?

Can you post your config and what you have done for settings in chrome/edge?

Sorry for that many (maybe stupid) questions, but I tried so much and I am not an expert with tools like this.
I would be so thankfully for help.

**Comment by HulkHoganNWO** [comment]
Ok, I think I managed to install it via pdm at windows.
Bot is now running - but unfortunatelly I always get the message "you have been banned" after login.

I use Chrome and this is my config:

chrome://version
`Überarbeitung | 81bc525b6a36d91ed7fe98a4b53c6f53c79adbb2-refs/branch-heads/6261_57@{#3}
Betriebssystem | Windows 10 Version 22H2 (Build 19045.4046)
JavaScript | V8 12.2.281.16
User-Agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36
Befehlszeile | "C:\Program Files\Google\Chrome\Application\chrome.exe" --flag-switches-begin --flag-switches-end
Programmdateipfad | C:\Program Files\Google\Chrome\Application\chrome.exe
Profilpfad | C:\Users\Benutzername\AppData\Local\Google\Chrome\User Data\Profile 6

config.yaml
`# browser configuration
browser:
  # https://peter.sh/experiments/chromium-command-line-switches/
  arguments:
    # https://stackoverflow.com/a/50725918/5116073
    - --disable-dev-shm-usage
    - --remote-debugging-port=9222
    - --no-sandbox
    # --headless
    # --start-maximized
  binary_location: C:\Program Files\Google\Chrome\Application\chrome.exe # path to custom browser executable, if not specified will be looked up on PATH
  extensions: [] # a list of .crx extension files to be loaded
  use_private_window: false
  user_data_dir: 'C:\Users\Benutzername\AppData\Local\Google\Chrome\User Data\'
  profile_name: 'Kleinanzeigen'

# login credentials
login:
  username: 'blabla@mail.com'
  password: 'password'`

1. I open Chrome, use the Chrome-Profile "Kleinanzeigen" go to kleinanzeigen.de, login in, go to ad-page
2. I close Chrome
3. Start kleinanzeigen-bot with a test-publishing ad. 
4. Chrome is opened by the bot, go to main page. And I think here I am already wrong, because the chrome that the bot opens is not the profile "Kleinanzeigen", it's called "Profil 1".
5. When I go to the login-page the "puzzle" appears and then I am banned.

**Comment by Heart1010** [comment]
I have more or less exactly the same - but using "Profile 1" (eventually you try it with "Profile 1" instead of "Kleinanzeigen" - login manually with "Profile 1" before....)

**Comment by HulkHoganNWO** [comment]
> I have more or less exactly the same - but using "Profile 1" (eventually you try it with "Profile 1" instead of "Kleinanzeigen" - login manually with "Profile 1" before....). **Or "Profile 6" - that's what is shown in your chrome info above.**

Thhaaaaaaaaank you!
Now it works (Profile 1).
It was a little bit confusing...  I tried so many profilnames. 

I am sooo happy now. Thank you all!

**Comment by kahironimashte** [comment]
> You probably just need:
> 
> ```
> C:\Program Files\Google\Chrome\Application\chrome.exe --remote-debugging-port=9222
> ```
> 
> to start chrome with the remote debugging port open.
> 
> The rest of the flags are for the config only. `--remote-debugging-port=9222` has a sending and a receiving end.
> 
> Thats as far as I can help you on windows, there might also be other issues you need to be able to debug yourself.

I made it work on Ubuntu 22.04. 

First I initiated chromium with a new profile: `chromium --profile-directory=Profile1` where `Profile1` is a name that is not used by any other profile yet.

Then I used the following settings for config. I use chromium, which is installed with snap by default:
```
browser:
  arguments:
    - --disable-dev-shm-usage
    - --remote-debugging-port=9222    
    - --no-sandbox
  binary_location: /snap/bin/chromium 
  extensions: [] 
  use_private_window: false
  user_data_dir: 'home/USERNAME/.config/chromium'
  profile_name: 'Profile1'
```
Start Chromium on the debugging-port `chromium --profile-directory=Profile1 --remote-debugging-port=9222` and log into Kleinanzeigen, keep the window (browser, terminal) open.

Then from the installation (source code) folder: `pdm run app publish --config /PATH/TO/CONFIG`

**Comment by sebthom** [comment]
Please try the latest release. It should solve these issues for now. I also documented how to re-use an open browser window at https://github.com/Second-Hand-Friends/kleinanzeigen-bot?tab=readme-ov-file#existing-browser

**Comment by knipknap** [comment]
Awesome, works perfectly on the first try now, Thanks a lot!

Just a heads up, the publishing pipeline doesn't work, so the download links are broken. I was able to find the latest version in the pipeline artifacts though, so was able to install anyway.

**Comment by ilyaZar** [comment]
@sebthom thanks a lot for solving this annoying thing, works like a gem on linux `OS: Linux Mint 21.2 x86_64` ! 

nodriver seems ultra promising as well !
