### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by dragonheart100** [Second-Hand-Friends/kleinanzeigen-bot#22]
I get this error
←[1;30m[INFO]←[0m Logging to [D:\unsortiert\Downloads\Kleinanzeigen-bot new\kleinanzeigen-bot.log]...
←[1;30m[INFO]←[0m App version: 0.1.dev1+g8e132d6
←[1;30m[INFO]←[0m Loading config from [D:\unsortiert\Downloads\Kleinanzeigen-bot new\config.yaml]...
←[1;30m[INFO]←[0m  -> found 19 categories
←[1;30m[ERROR]←[0m ←[31mTypeError: string indices must be integers←[0m
[7640] Failed to execute script '__main__' due to unhandled exception!

**Comment by sebthom** [comment]
Can you please re-run with --verbose and post the stacktrace.

**Comment by dragonheart100** [comment]
←[1;30m[INFO]←[0m Logging to [D:\unsortiert\Downloads\Kleinanzeigen-bot new\kleinanzeigen-bot.log]...
←[1;30m[INFO]←[0m App version: 0.1.dev1+g8e132d6
←[1;30m[DEBUG]←[0m ←[32mLoading [kleinanzeigen_bot.resources.config_defaults.yaml]...←[0m
←[1;30m[INFO]←[0m Loading config from [D:\unsortiert\Downloads\Kleinanzeigen-bot new\config.yaml]...
←[1;30m[DEBUG]←[0m ←[32mLoading categories from [kleinanzeigen_bot.resources.categories.yaml]...←[0m
←[1;30m[INFO]←[0m  -> found 19 categories
←[1;30m[ERROR]←[0m ←[31mTraceback (most recent call last):
  File "kleinanzeigen_bot\__main__.py", line 8, in <module>
  File "kleinanzeigen_bot\__init__.py", line 480, in main
  File "kleinanzeigen_bot\__init__.py", line 64, in run
  File "kleinanzeigen_bot\__init__.py", line 268, in load_config
TypeError: string indices must be integers
←[0m
[3288] Failed to execute script '__main__' due to unhandled exception!

**Comment by sebthom** [comment]
It seems to fail here https://github.com/Second-Hand-Friends/kleinanzeigen-bot/blob/56646db5b57e4acf27384747f130c6ead2979de2/kleinanzeigen_bot/__init__.py#L267-L270 in line 268 where the username is loaded.

How did you specify your login details in the config.yaml file? It should look something like this:

```yaml
login:
  username: "my_email@example.com"
  password: "my_password_goes_here"
```

**Comment by dragonheart100** [comment]
Thank you, I forgot the quotation marks.
The script worked smoothly now and I was able to start an ad.
