### ISSUE TITLE
[ENH]  Docker with Wayland

### ISSUE THREAD

**Issue by lamyergeier** [Second-Hand-Friends/kleinanzeigen-bot#245]
### 😕 Addressed Problem

Most Linux Desktop use Wayland display server.

### 💡 Suggested Solution

Is it possible to use Docker installation with Wayland or xwayland? If yes please tell how? 

I am using Fedora 39.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sebthom** [comment]
Please ask this question in the forum I can't answer this.
