### ISSUE TITLE
[BUG] Increase Timeout

### ISSUE THREAD

**Issue by lamyergeier** [Second-Hand-Friends/kleinanzeigen-bot#251]
### ✔️ Expected Behaviour

I execute the bot from terminal, and it opens a new window of chrome, where I try to manually solve the puzzle (in less than 2 seconds) and I enter my credentials manually (as the auto login is always leading to account getting locked).

### 🐞 Actual Behaviour

I  get this message (even though I get no advertisement)

` TimeoutException: Message: Loading page failed, it still shows fullscreen ad.`

And the browser window closses,

### 📋 Steps to Reproduce

I execute the bot from terminal, and it opens a new window of chrome, where I try to manually solve the puzzle (in less than 2 seconds) and I enter my credentials manually (as the auto login is always leading to account getting locked), but I get this timeout exception so fast that the browser window closes. 

### 📺 What browsers are you seeing the problem on? (if applicable)

Chrome

### 💻 What operating systems are you seeing the problem on? (if applicable)

Fedora 39

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by TylonHH** [comment]
And if you are able to solve this, your session is banned, fortunately not the account

**Comment by kahironimashte** [comment]
I am on Ubuntu 22.04. Does this bug also appear on Windows-machines?

**Comment by FullHD23** [comment]
> I am on Ubuntu 22.04 and share the observation. Does this bug also appear on Windows-machines?

Yes, had the same problem on windows. I changed to headless and to a already logged in session which seems to help.

**Comment by kriz99** [comment]
> I changed to headless and to a already logged in session which seems to help.

Could you explain how to use a "already logged in session", please?

**Comment by sebthom** [comment]
Should be solved by latest release.
