### ISSUE TITLE
[BUG] ElementClickInterceptedException:

### ISSUE THREAD

**Issue by mhmuc1** [Second-Hand-Friends/kleinanzeigen-bot#252]
### ✔️ Expected Behaviour

Republishing of previously downloaded adds

### 🐞 Actual Behaviour

While publishing the add the following error occurs:
`ElementClickInterceptedException: Message: element click intercepted: Element <input id="radio-buy-now-no" type="radio" class="jsx-3869256946 BuyNowRadio--Input "> is not clickable at point (199, 875). Other element would receive the click: <div aria-hidden="true" class="jsx-666287395 Modal--backdrop"></div>
  (Session info: chrome=120.0.6099.216)`

### 📋 Steps to Reproduce

Start the bot with publish-option

### 📺 What browsers are you seeing the problem on? (if applicable)

Chrome

### 💻 What operating systems are you seeing the problem on? (if applicable)

Linux

### 📃 Relevant log output (if applicable)

[INFO] Publishing ad 'REMOVED FOR PRIVACY'...
[INFO]  ... pausing for 2000 ms ...
[INFO]  ... pausing for 2000 ms ...
[INFO]  ... pausing for 2000 ms ...
[INFO]  ... pausing for 1744 ms ...
[INFO]  ... pausing for 1569 ms ...
[INFO]  ... pausing for 1721 ms ...
[ERROR] ElementClickInterceptedException: Message: element click intercepted: Element <input id="radio-buy-now-no" type="radio" class="jsx-3869256946 BuyNowRadio--Input "> is not clickable at point (199, 875). Other element would receive the click: <div aria-hidden="true" class="jsx-666287395 Modal--backdrop"></div>
  (Session info: chrome=120.0.6099.216)
Stacktrace:
#0 0x55ba37097023 <unknown>
#1 0x55ba36d725c7 <unknown>
#2 0x55ba36dbbb4d <unknown>
#3 0x55ba36dba2f3 <unknown>
#4 0x55ba36db85fc <unknown>
#5 0x55ba36db7c3b <unknown>
#6 0x55ba36dad390 <unknown>
#7 0x55ba36ddcdd2 <unknown>
#8 0x55ba36dacdbe <unknown>
#9 0x55ba36ddd17e <unknown>
#10 0x55ba36df6a90 <unknown>
#11 0x55ba36ddcb53 <unknown>
#12 0x55ba36daac6d <unknown>
#13 0x55ba36dac4e2 <unknown>
#14 0x55ba3706be14 <unknown>
#15 0x55ba3706f069 <unknown>
#16 0x55ba3706eb48 <unknown>
#17 0x55ba3706f515 <unknown>
#18 0x55ba3705e29f <unknown>
#19 0x55ba3706f89e <unknown>
#20 0x55ba37048126 <unknown>
#21 0x55ba37087de5 <unknown>
#22 0x55ba37087fcb <unknown>
#23 0x55ba370965af <unknown>
#24 0x7f655ff9e044 <unknown>

[8] Failed to execute script '__main__' due to unhandled exception!
16:03:28 Error - exited with status 0 at line 23:
   20
   21   cd /mnt/data
   22
   23   /opt/kleinanzeigen-bot --config $CONFIG_FILE "$@"

C:\Docker\KleinanzeigenBot>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by DenisLanz** [comment]
+1
 not using shipping options I was able to publish  - changed to the shipping option afterwards manually as a workaround.

**Comment by FullHD23** [comment]
+1 I have the same problem and I can confirm that it works without shipping option.

**Comment by sebthom** [comment]
Please try the latest version. In case the issue persist please open a new issue with full error logs when running in verbose mode via `--verbose`
