### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by statementer** [Second-Hand-Friends/kleinanzeigen-bot#257]
### ✔️ Expected Behaviour

upon entering ` use_private_window: false` into config.yaml i expect it to start in my default browser that is logged in. I want it to start in my logged in browser because the auto log-in function with credential always gets me blocked by kleinanzeigen.

### 🐞 Actual Behaviour

it starts a new browser profile. 

### 📋 Steps to Reproduce

run the default config with the essential input and only change  `use_private_window: false` 

### 📺 What browsers are you seeing the problem on? (if applicable)

Chrome, Microsoft Edge

### 💻 What operating systems are you seeing the problem on? (if applicable)

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sebthom** [comment]
This is not possible as the browser needs to be running in debug mode. You can try this approach https://github.com/Second-Hand-Friends/kleinanzeigen-bot/issues/219#issuecomment-1979286546
