### ISSUE TITLE
[BUG] No config.yaml after Installation Win10

### ISSUE THREAD

**Issue by HulkHoganNWO** [Second-Hand-Friends/kleinanzeigen-bot#260]
### ✔️ Expected Behaviour

I followed the installation-guide for windows. 

Windows 10, Version 22H2 Build 19045.3930
Edge is installed

### 🐞 Actual Behaviour

Can't find the config.yaml file after installation.

At my installation-path "d:\" there is "kleinanzeigen-bot.exe" but no config-file.

### 📋 Steps to Reproduce

Opened terminal via "cmd", started as admin
Copy/Paste: 

D:\>curl -L https://github.com/Second-Hand-Friends/kleinanzeigen-bot/releases/download/latest/kleinanzeigen-bot-windows-amd64.exe -o kleinanzeigen-bot.exe
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 17.2M  100 17.2M    0     0  8374k      0  0:00:02  0:00:02 --:--:-- 12.6M

D:\>kleinanzeigen-bot --help

 _    _      _                           _                       _           _
| | _| | ___(_)_ __   __ _ _ __  _______(_) __ _  ___ _ __      | |__   ___ | |_
| |/ / |/ _ \ | '_ \ / _` | '_ \|_  / _ \ |/ _` |/ _ \ '_ \ ____| '_ \ / _ \| __|
|   <| |  __/ | | | | (_| | | | |/ /  __/ | (_| |  __/ | | |____| |_) | (_) | |_
|_|\_\_|\___|_|_| |_|\__,_|_| |_/___\___|_|\__, |\___|_| |_|    |_.__/ \___/ \__|
                                           |___/
                         https://github.com/Second-Hand-Friends/kleinanzeigen-bot

Usage: kleinanzeigen-bot COMMAND [OPTIONS]
.....

### 💻 What operating systems are you seeing the problem on? (if applicable)

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sebthom** [comment]
The config file is created when you run `kleinanzeigen_bot publish` the first time.
