### ISSUE TITLE
The list of categories appears to be incomplete

### ISSUE THREAD

**Issue by knipknap** [Second-Hand-Friends/kleinanzeigen-bot#261]
### ✔️ Expected Behaviour

I am looking for the category "Heimwerken", but it is not included here:
https://github.com/Second-Hand-Friends/kleinanzeigen-bot/blob/main/kleinanzeigen_bot/resources/categories.yaml

Any hint on whee to find it?

### 🐞 Actual Behaviour

The allowed value should be documented

### 📋 Steps to Reproduce

Open the link, see that the category is not in the list.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sebthom** [comment]
@knipknap you are welcome to provide a PR to extend the list
