### ISSUE TITLE
[BUG] Virus Warning with latest

### ISSUE THREAD

**Issue by TylonHH** [Second-Hand-Friends/kleinanzeigen-bot#269]
I get virus warning and windows defender removes immediately the file 

Program:Win32/Wacapew.C!ml

[VirusTotal Link](https://www.virustotal.com/gui/file/0a01106f1849709e66e8c6122e2f0d5fd001dabfb2f9b1ad6456ad2e6e680f82/detection)

**Comment by IchSkill** [comment]
I also got this on the previous version, just add an exception for the files

**Comment by sebthom** [comment]
This is a Windows Defender false positive. There are lots of reports where it miss-detects pyinstaller exes as trojans.
I don't think there is anything we can do.

For what it's worth, I added a build step at the beginning which installs/starts the clamav daemon. so in the unlikely case one of the python dependencies should contain a trojan this should catch it and preventing a release build.

**Comment by sebthom** [comment]
The release now contains a `kleinanzeigen-bot-windows-amd64-uncompressed.exe` file which is not compressed using upx. maybe this prevents the false positive being triggered.
