### ISSUE TITLE
[ERROR] TimeoutError: No HTML element found using CSS selector '.l-splitpage' within 5 seconds.

### ISSUE THREAD

**Issue by PlanetDyna** [Second-Hand-Friends/kleinanzeigen-bot#275]
### ✔️ Expected Behaviour

Search for new ads 

### 🐞 Actual Behaviour

Error appears
[ERROR] TimeoutError: No HTML element found using CSS selector '.l-splitpage' within 5 seconds.

### 📋 Steps to Reproduce

Nothing

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sebthom** [comment]
Closing issue for now. If the issue still persists with the latest version, feel free to re-open the ticket and provide a complete  error message/stacktrace when running the bot with --verbose.
