### ISSUE TITLE
[BUG] VALUE NEGOTIABLE IS NOT WORKING

### ISSUE THREAD

**Issue by PlanetDyna** [Second-Hand-Friends/kleinanzeigen-bot#276]
### ✔️ Expected Behaviour

VALUE FOR PRICE NEGOTIABLE

### 🐞 Actual Behaviour

It is changed to NEGOTIABLE and then changes again to FIXED.

### 📋 Steps to Reproduce

Nothing here

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by RoonniieeX** [comment]
I can confirm that!
