### ISSUE TITLE
[BUG] Error message with more than 25 adverts/display on 2+ pages

### ISSUE THREAD

**Issue by PlanetDyna** [Second-Hand-Friends/kleinanzeigen-bot#278]
### ✔️ Expected Behaviour

All adverts are downloaded. Not just the one on page 1.

### 🐞 Actual Behaviour

Error message/stop the download if the adverts are on page 2 for example.

### 📋 Steps to Reproduce

Create more than 25 adverts.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by euberdeveloper** [comment]
Isn't it a duplicate of: #263

**Comment by TylonHH** [comment]
As I have also more then 25 ads I searched here and fpund all this related issues:
https://github.com/Second-Hand-Friends/kleinanzeigen-bot/issues/170
https://github.com/Second-Hand-Friends/kleinanzeigen-bot/issues/149

This is the error message I got. I hope this helps someone to debug:
```[INFO] It seems like you have many ads!```
```[ERROR] TimeoutError: No HTML elements found using CSS selector 'button.jsx-2828608826' within 5 seconds.```

I use the latetest exed for windows.

**Comment by provinzio** [comment]
Does the PR fix the issue? @PlanetDyna

**Comment by sebthom** [comment]
Closing issue as it is supposed to be fixed by #298. Feel free to re-open if issue still persists
