### ISSUE TITLE
Support additional attributes in categories

### ISSUE THREAD

**Issue by DenisLanz** [Second-Hand-Friends/kleinanzeigen-bot#28]
As mentioned in #5 there are several categories which need additional attributes to be filled in order to publish an ad. I've mainly stumbled over these mainly in the two categories Bicycle as well as categories, where there is only one additional dropdown  - while exploring a bit in other categories I found even more fields in the House category, which is probably more of an edge-case and I didn't explore them further. 

**Auto, Rad & Boot > Fahrräder & Zubehör > Kinder**
```
id="fahrraeder.type_s"
name="attributeMap[fahrraeder.type_s]"
``` 

**Elektronik > Foto > Kamera & Zubehör**
```
id="foto.condition_s"
name="attributeMap[foto.condition_s]"
```

As far as I can see, they don't have much in common, besides having an attributeMap in their name attribute, maybe that would be something to loop through when defined these maps in the ads config.

**Comment by OlegLoewen** [comment]
Is there currently no workaround for this issue? I'm  not able to create an ad for category Haus (195/203) because of missing sub categories.
