### ISSUE TITLE
[BUG] There are currently no ads on your profile!

### ISSUE THREAD

**Issue by TylonHH** [Second-Hand-Friends/kleinanzeigen-bot#290]
### ✔️ Expected Behaviour

capture my ads

### 🐞 Actual Behaviour

doesnt recognize my ads

### 📋 Steps to Reproduce

I used the latest 2c7d165

### 📺 What browsers are you seeing the problem on? (if applicable)

Chrome

### 💻 What operating systems are you seeing the problem on? (if applicable)

Windows

### 📃 Relevant log output (if applicable)

No usefull hints with --verbose

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by provinzio** [comment]
I couldn't reproduce the error using edge as the browser. Do you happen to have more hints where the bug could come from?
