### ISSUE TITLE
[BUG] all shipping_options are enabled although just one is in the yaml

### ISSUE THREAD

**Issue by TylonHH** [Second-Hand-Friends/kleinanzeigen-bot#292]
### ✔️ Expected Behaviour

Just use the shipping_options wich are listed in the yaml

### 🐞 Actual Behaviour

all shipping_options are enabled within the ad

### 📋 Steps to Reproduce

Enable shipping option within an ad, like DHL 5,49€. Export this. Check YAML. Force for renew.

### 📺 What browsers are you seeing the problem on? (if applicable)

Chrome

### 💻 What operating systems are you seeing the problem on? (if applicable)

Windows

### 📃 Relevant log output (if applicable)

```
price: 5
price_type: FIXED
shipping_type: SHIPPING
shipping_costs: 5.49
shipping_options:
  - DHL_2
sell_directly:
```
![grafik](https://github.com/Second-Hand-Friends/kleinanzeigen-bot/assets/18073299/ce0d272b-736e-4fba-b728-43cc8b825e92)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bochen87** [comment]
same issue
