### ISSUE TITLE
browser set up [BUG] 

### ISSUE THREAD

**Issue by laeaexxx** [Second-Hand-Friends/kleinanzeigen-bot#294]
### ✔️ Expected Behaviour

bot downloads ads

### 🐞 Actual Behaviour

when using the command "pdm app run dowanload" there is a weird error message

### 📋 Steps to Reproduce

idk how its just on my linux rpi

### 💻 What operating systems are you seeing the problem on? (if applicable)

Linux

### 📃 Relevant log output (if applicable)

 pdm run app download

 _    _      _                           _                       _           _
| | _| | ___(_)_ __   __ _ _ __  _______(_) __ _  ___ _ __      | |__   ___ | |_
| |/ / |/ _ \ | '_ \ / _` | '_ \|_  / _ \ |/ _` |/ _ \ '_ \ ____| '_ \ / _ \| __|
|   <| |  __/ | | | | (_| | | | |/ /  __/ | (_| |  __/ | | |____| |_) | (_) | |_
|_|\_\_|\___|_|_| |_|\__,_|_| |_/___\___|_|\__, |\___|_| |_|    |_.__/ \___/ \__|
                                           |___/
                         https://github.com/Second-Hand-Friends/kleinanzeigen-bot

[INFO] Logging to [/home/laeaexx/kleinanzeigen-bot/kleinanzeigen_bot.log]...
[INFO] App version: 2024+1297428
[INFO] Python version: 3.11.2 (main, Mar 13 2023, 12:18:29) [GCC 12.2.0]
[WARNING] You provided no ads selector. Defaulting to "new".
[INFO] Loading config from [/home/laeaexx/kleinanzeigen-bot/config.yaml]...
[INFO]  -> found 145 categories
[INFO] Creating Browser session...
[INFO]  -> Chrome binary location: /usr/bin/chromium-browser
[INFO] -> Setting chrome prefs [/tmp/uc_k4jndpv2/Default/Preferences]...
[ERROR] Exception:
                ---------------------
                Failed to connect to browser
                ---------------------
                One of the causes could be when you are running as root.
                In that case you need to pass no_sandbox=True

successfully removed temp profile /tmp/uc_k4jndpv2

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by apeltzer** [comment]
Agree, same error here.

**Comment by laeaexxx** [comment]
So how do I fix it?

**Comment by apeltzer** [comment]
The nodriver package got an update to 0.27.4, maybe that helps. Though its not on pypi yet https://github.com/ultrafunkamsterdam/nodriver/commit/bb0fcafd9497bae3f3f81e011e56f5a5a5c0fad3

**Comment by laeaexxx** [comment]
still cant fix that shit pls help

**Comment by apeltzer** [comment]
Upgrading to 0.27.4 didnt help either, no luck for me.

**Comment by apeltzer** [comment]
Using the latest version as automatically build from releases works for me again 👍🏻

**Comment by laeaexxx** [comment]
> Using the latest version as automatically build from releases works for me again 👍🏻 

What exactly did u do

**Comment by provinzio** [comment]
@laeaexxx apeltzer refers to the binary executables which are automatically build on every new update to the main branch. You can find them unter "Releases" which is on the right side of the repo home page

On the ["Releases" page](https://github.com/Second-Hand-Friends/kleinanzeigen-bot/releases) the files. Please select the executable file according to your machine.

The [usage](https://github.com/Second-Hand-Friends/kleinanzeigen-bot/releases) is similar to the pdm version. In a terminal you can call the executable like `C:\myexecutable.exe download --force`.

**Comment by Vel-San** [comment]
FYI A quick fix for this is to open Chrome in debugging mode as well.

## Chrome Launch from Terminal

>open -a "Google Chrome" --args --remote-debugging-port=9222

## Bot Config

>arguments: ["-no-sandbox", "--remote-debugging-port=9222"]
