### ISSUE TITLE
[BUG] Cannot run in headless mode

### ISSUE THREAD

**Issue by bochen87** [Second-Hand-Friends/kleinanzeigen-bot#297]
### ✔️ Expected Behaviour

When uncommenting --headless in config, it should be able to run in headless mode

### 🐞 Actual Behaviour

whenever i run in headless mode with config, it has some error and closes. Whenever i change the config in code to headless = True, then it runs into a captcha issue

### 📋 Steps to Reproduce

uncomment -- headless from config and try or set headless = True in https://github.com/Second-Hand-Friends/kleinanzeigen-bot/blob/822d3b7e7c6721feea26c523d5abc20cc50b32f9/src/kleinanzeigen_bot/web_scraping_mixin.py#L152

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bochen87** [comment]
I guess maybe related to this: https://github.com/ultrafunkamsterdam/undetected-chromedriver/issues/1848

**Comment by sebthom** [comment]
Running the bot in headless mode is not supported as there are situations where manual interaction is required (captchas, device verification).

**Comment by bochen87** [comment]
I see. I added a virtual display, where i let it run. but it might be an issue in required interactions :-/
