### ISSUE TITLE
[BUG] On Download: Error  Failed to execute script '__main__' due to unhandled exception!

### ISSUE THREAD

**Issue by Saghalt** [Second-Hand-Friends/kleinanzeigen-bot#312]
### ✔️ Expected Behaviour

Download of ads

### 🐞 Actual Behaviour

The ads list is fetched
Then the single add is opened and breaks down with error message:  Failed to execute script '__main__' due to unhandled exception!

### 📋 Steps to Reproduce

Execute kleinanzeigen-bot download -v

### 📺 What browsers are you seeing the problem on? (if applicable)

Microsoft Edge

### 💻 What operating systems are you seeing the problem on? (if applicable)

Windows

### 📃 Relevant log output (if applicable)

[INFO] Loaded 35 ads
[INFO] Start fetch task for your unsaved ads!
[DEBUG]  -> Opening [https://www.kleinanzeigen.de/s-anzeige/wasserschuhe-rot-blau-gr*************]...
[INFO]  ... pausing for 1580 ms ...
[INFO] Deleting current folder of ad...
[INFO] New directory for ad created at downloaded-ads\ad_27***.
[INFO] Extracting information from ad with title "Wasserschuhe rot-blau Gr*****"
[DEBUG] Closing Browser session...
[INFO] terminated browser with pid 11292 successfully
[ERROR] Traceback (most recent call last):
  File "kleinanzeigen_bot\__main__.py", line 9, in <module>
  File "kleinanzeigen_bot\__init__.py", line 864, in main
  File "asyncio\base_events.py", line 684, in run_until_complete
  File "kleinanzeigen_bot\__init__.py", line 114, in run
  File "kleinanzeigen_bot\__init__.py", line 823, in download_ads
  File "kleinanzeigen_bot\extract.py", line 49, in download_ad
  File "kleinanzeigen_bot\extract.py", line 236, in _extract_ad_page_info
  File "kleinanzeigen_bot\extract.py", line 293, in _extract_special_attributes_from_ad_page
  File "json\__init__.py", line 346, in loads
  File "json\decoder.py", line 337, in decode
  File "json\decoder.py", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Saghalt** [comment]
Latest version was used based on https://github.com/Second-Hand-Friends/kleinanzeigen-bot/commit/0f87e5573aa1f7650bcc43bfafb7c5d8b76b308e

**Comment by Saghalt** [comment]
Seems like the details could not be extracted.

The webpage source is:
            <div class="splitlinebox l-container-row" id="viewad-details">
                    <ul class="addetailslist">
                        <li class="addetailslist--detail">
                                        Art<span class="addetailslist--detail--value" >
                                        Badeschuhe</span>
                                    </li>
                                <li class="addetailslist--detail">
                                        Farbe<span class="addetailslist--detail--value" >
                                        Rot</span>
                                    </li>
                                <li class="addetailslist--detail">
                                        Größe<span class="addetailslist--detail--value" >
                                        30</span>
                                    </li>
                                <li class="addetailslist--detail">
                                        Zustand<span class="addetailslist--detail--value" >
                                        Gut</span>
                                    </li>
                                </ul>
                </div>
I hope this helps

**Comment by blautob** [comment]
can confirm same error here

**Comment by Saghalt** [comment]
@sebthom I'vee done a small contribution to fix the issue. I hope you like it. Thanks for providing this powerful tool :-)

**Comment by sebthom** [comment]
Fixed by #312
