### ISSUE TITLE
Create ad file based on existing published ad

### ISSUE THREAD

**Issue by OlegLoewen** [Second-Hand-Friends/kleinanzeigen-bot#32]
**Why do we need this?**
Sometimes it's more convenient to create an ad via the official ebay-kleinanzeigen app/website. Yet, you still want to add this ad to your kleinanzeigen-bot list of ads. 

**Solution proposal:**
Introduce a new command download where you pass the ad ID. Hence, the description, properties, photos and categories shall be extracted and added to an ad-file.

**Comment by tobiasschuerg** [comment]
I second that!

btw.: hi @OlegLoewen 😂

**Comment by sebthom** [comment]
Yes, this would be useful. Contributions are welcome.
