### ISSUE TITLE
[BUG] ValueError when downloading ads

### ISSUE THREAD

**Issue by cbshopper** [Second-Hand-Friends/kleinanzeigen-bot#323]
### ✔️ Expected Behaviour

kleinanzeigen-bot download

### 🐞 Actual Behaviour

[INFO] Extracting information from ad with title "Siemns RT10 Transitor Radio Oldtimer"
[ERROR] ValueError: dictionary update sequence element #0 has length 1; 2 is required
[30960] Failed to execute script '__main__' due to unhandled exception!

### 📋 Steps to Reproduce

kleinanzeigen-bot download
Browser is loaded
Ads are listet
Error:  ValueError: dictionary update sequence element #0 has length 1; 2 is required

### 📺 What browsers are you seeing the problem on? (if applicable)

Chrome

### 💻 What operating systems are you seeing the problem on? (if applicable)

Windows

### 📃 Relevant log output (if applicable)

[INFO] Logging to [C:\ProgrammeXL\Office\Kleinanzeigen\kleinanzeigen-bot.log]...
[INFO] App version: 2024+c127262
[INFO] Python version: 3.12.1 (tags/v3.12.1:2305ca5, Dec  7 2023, 22:03:25) [MSC v.1937 64 bit (AMD64)]
[WARNING] You provided no ads selector. Defaulting to "new".
[INFO] Loading config from [C:\ProgrammeXL\Office\Kleinanzeigen\config.yaml]...
[INFO]  -> found 145 categories
[INFO] Creating Browser session...
[INFO]  -> Chrome binary location: C:\Program Files\Google\Chrome\Application\chrome.exe
[INFO]  -> Browser profile name: profile1
[INFO]  -> Browser user data dir: c:\Users\crrbl\AppData\Local\Google\Chrome\User Data\
[INFO] New Browser session is ws://127.0.0.1:33749/devtools/browser/eedd1c4e-e63e-46d5-aed5-2d1153e2d640
[INFO] Checking if already logged in...
[INFO] Already logged in as [cbshome@freenet.de]. Skipping login.
[INFO] Scanning your ad overview...
[INFO]  ... pausing for 2453 ms ...
[INFO]  ... pausing for 2441 ms ...
[INFO] It seems like all your ads fit on one overview page.
[INFO] 3 ads were found!
[INFO] Searching for ad config files...
[INFO]  -> found 0 ad config files
[INFO] Start fetch task for your unsaved ads!
[INFO]  ... pausing for 2173 ms ...
[INFO] Created ads directory at ./downloaded-ads.
[INFO] New directory for ad created at downloaded-ads\ad_2827968602.
[INFO] Extracting information from ad with title "Siemns RT10 Transitor Radio Oldtimer"
[ERROR] ValueError: dictionary update sequence element #0 has length 1; 2 is required
[30960] Failed to execute script '__main__' due to unhandled exception!
successfully removed temp profile c:\Users\crrbl\AppData\Local\Google\Chrome\User Data\

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sebthom** [comment]
Please run the bot with --verbose and paste the complete error message.

**Comment by Saghalt** [comment]
error message run with verbose:
  File ".\kleinanzeigen_bot\__init__.py", line 118, in run
    await self.download_ads()
  File ".\kleinanzeigen_bot\__init__.py", line 873, in download_ads
    await ad_extractor.download_ad(ad_id)
  File ".\kleinanzeigen_bot\extract.py", line 49, in download_ad
    info = await self._extract_ad_page_info(new_base_dir, ad_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".\kleinanzeigen_bot\extract.py", line 236, in _extract_ad_page_info
    info['special_attributes'] = await self._extract_special_attributes_from_ad_page()
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".\kleinanzeigen_bot\extract.py", line 293, in _extract_special_attributes_from_ad_page
    special_attributes = dict(item.split(":") for item in special_attributes_str.split("|") if ":" in item)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: dictionary update sequence element #0 has length 1; 2 is required
