### ISSUE TITLE
Request: Please Add new categories because the are not listetet

### ISSUE THREAD

**Issue by raindancer2204** [Second-Hand-Friends/kleinanzeigen-bot#331]
### 😕 Addressed Problem

Adding new categories as they cannot be selected.

### 💡 Suggested Solution

Can someone please add some categorys?  I found this on this Link: [ebaykleinanzeigen categorys](https://www.kleinanzeigen.de/s-kategorien.html).

I dont know if the numbers are correct.

#Familie, Kind & Baby
Baby- & Kinderkleidung (4.404.399)
Baby- & Kinderschuhe (1.148.029)
Baby-Ausstattung (827.224)
Babyschalen & Kindersitze (210.755)
Kinderwagen & Buggys (188.676)
Weiteres Familie, Kind & Baby (469.443)

# Freizeit, Hobby & Nachbarschaft
Freizeit, Hobby & Nachbarschaft (5.013.657)
Modellbau (396.118)

Thanks a Lot

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by 0verEngineer** [comment]
Hey, check my howTo: https://github.com/Second-Hand-Friends/kleinanzeigen-bot/discussions/336

**Comment by sebthom** [comment]
Done
