### ISSUE TITLE
[BUG] Shipping type not set by bot in category 153/157

### ISSUE THREAD

**Issue by BER4452** [Second-Hand-Friends/kleinanzeigen-bot#332]
### ✔️ Expected Behaviour

Bot should set shipping type to SHIPPING in category Mode & Beauty > Uhren & Schmuck > Schmuck (153/157)

### 🐞 Actual Behaviour

Bot is doing everything correctly incl. special characters but fails to set shipping type to SHIPPING. Nothing is selected. Thus, the ad can not be published and the bot fails.

### 📋 Steps to Reproduce

Try to publish an article in the category (153/157) with shipping type SHIPPING

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by BER4452** [comment]
It might be connected to the use of a business "gewerblicher" account, free version without premium packages. It worked perfectly with my private account. Can this be adapted?

**Comment by sebthom** [comment]
If you are a commercial seller please either use one of the existing commercial tools to sync your ads or provide a PR to fix the code so everyone can participate from it.
