### ISSUE TITLE
[ENH] Option to disable deletion of ads

### ISSUE THREAD

**Issue by blautob** [Second-Hand-Friends/kleinanzeigen-bot#338]
### 😕 Addressed Problem

Sometimes due to missing fileds or whatever reason my ads cannot be republished after they have been downloaded. the bot however deletes the ad from kleinanzeigen

### 💡 Suggested Solution

a command line option that prohibits the deletion of the ads.
i rather have two ads (one old and one republished) then no ad at all

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Saghalt** [comment]
Hi @blautob,

won't parameters like "publish --keep-old --ads=due" already solve your issue?

**Comment by sebthom** [comment]
Ads are now by default deleted after successful publshing. This behaviour can now be controlled in the config.yaml file:

https://github.com/Second-Hand-Friends/kleinanzeigen-bot/blob/b2599771989aa5878824e6396ebd0d18321efc5c/src/kleinanzeigen_bot/resources/config_defaults.yaml#L29-L31
