### ISSUE TITLE
[BUG] Kleinanzeigen login is required 2 times in a row

### ISSUE THREAD

**Issue by 0verEngineer** [Second-Hand-Friends/kleinanzeigen-bot#339]
### ✔️ Expected Behaviour

Login works

### 🐞 Actual Behaviour

First login works and second one does not work and it will quit because it cannot detect a HTML Element

### 📋 Steps to Reproduce

Try to run the bot

### 📺 What browsers are you seeing the problem on? (if applicable)

Chrome

### 💻 What operating systems are you seeing the problem on? (if applicable)

Linux, MacOS

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by student-sx** [comment]
Same problem too. I tried to login manually before starting the bot, but this doesn't work neither. Any workaround so far?

**Comment by 0verEngineer** [comment]
I created a pull request with a fix but the double login is not required for me anymore, is it fixed for all of you guys?

**Comment by Tone866** [comment]
Yes, I noticed the same.
Tried it at 5. november - no double login required this time.

**Comment by student-sx** [comment]
For me the same: No double login anymore, but now I have [this](https://github.com/Second-Hand-Friends/kleinanzeigen-bot/issues/346) issue.
