### ISSUE TITLE
[BUG] When "TYPE: WANTED" then SHIPPING INPUT is ignored

### ISSUE THREAD

**Issue by thu-dong** [Second-Hand-Friends/kleinanzeigen-bot#349]
### ✔️ Expected Behaviour

shipping input from yaml file should be read into the browser session

### 🐞 Actual Behaviour

shipping input is ignored

### 📋 Steps to Reproduce

If I want something instead of selling I'd like to create an ad of TYPE:WANTED. Sadly, the shipping input is ignored.

These are my input parameters that do NOT work. It works only if "type: OFFER" instead of "type: WANTED"
* * *
active: true
type: WANTED
title: Apple Airpods
description: 

category: 161/168

price: 6
price_type: FIXED

special_attributes:

shipping_type: SHIPPING
shipping_costs: 4
shipping_options:
sell_directly: true

images:
  - '*.JPG'

contact:
  name: 
  street:
  zipcode: 
  phone: 

republication_interval: 1

id: 
created_on: 
updated_on:

**Comment by sebthom** [comment]
ads of type WANTED do not support regular shipping cost settings, they are actually implemented as "special attributes". Anyways. I changed the code so that the shipping_type value is set as special attribute now.
