### ISSUE TITLE
[BUG] Shipping Options exception

### ISSUE THREAD

**Issue by Airwave1981** [Second-Hand-Friends/kleinanzeigen-bot#352]
### ✔️ Expected Behaviour

I got an exception when the bot selects the shipping options with codeline:

            await self.web_click(By.CSS_SELECTOR, '[class*="jsx-3900439816"]')

I searched in the code and replacing the upper lines with that  (line 528+533 in src\kleinanzeigen_bot\__init__.py):

            await self.web_click(By.CSS_SELECTOR, '[class*="jsx-963945432 SelectionButton"]')

should get the script working again.

### 🐞 Actual Behaviour

Termination

### 📋 Steps to Reproduce

Run with shipping options like:

shipping_type: SHIPPING
shipping_costs: 5.00
shipping_options: [Hermes_S]
sell_directly: true

### 📺 What browsers are you seeing the problem on? (if applicable)

Microsoft Edge

### 💻 What operating systems are you seeing the problem on? (if applicable)

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sebthom** [comment]
A pull request with a fix is welcome.

**Comment by sebthom** [comment]
I think this is solved already
