### ISSUE TITLE
Element id='postad-step1-sbmt' not found

### ISSUE THREAD

**Issue by jniggemann** [Second-Hand-Friends/kleinanzeigen-bot#39]
App version: 0.1.dev1+g9196ed4

Not reproducible, ~ 80% of the time publishing doesn't work 
`[ERROR] NoSuchElementException: Message: Element id='postad-step1-sbmt' not found`

**Comment by sebthom** [comment]
It looks like something changed on the website. it now randomly fails when selecting the category. I didn't touch that part of the code in the bot.

**Comment by sebthom** [comment]
Can you try the latest build and check if the error is gone?

**Comment by jniggemann** [comment]
Great, it works.
On 2 occasions I noticed problems with image upload (2 of 15 images in an ad and 3 of 6 iamges in an ad). I uploaded manually and all went well.

**Comment by sebthom** [comment]
Thanks for the feedback. Closing the issue for now. Reopen if the error re-appears.

**Comment by Barsch666** [comment]
Got the same Problem:
> 2023-01-14 14:58:51,205 [INFO] App version: 0.1.dev1+gf85aeda
> 2023-01-14 15:00:27,676 [ERROR] NoSuchElementException: Message: Element id='postad-step1-sbmt' not found
Please fix ist in the main Version with the [workaround](https://github.com/Second-Hand-Friends/kleinanzeigen-bot/commit/e4f4feb005146b5b7187425794715a2815e6ce12), thanks.

Or I have to leran to compail the windows version!

**Comment by rockodd** [comment]
> Got the same Problem:
> 
> > 2023-01-14 14:58:51,205 [INFO] App version: 0.1.dev1+gf85aeda
> > 2023-01-14 15:00:27,676 [ERROR] NoSuchElementException: Message: Element id='postad-step1-sbmt' not found
> > Please fix ist in the main Version with the [workaround](https://github.com/Second-Hand-Friends/kleinanzeigen-bot/commit/e4f4feb005146b5b7187425794715a2815e6ce12), thanks.
> 
> Or I have to leran to compail the windows version!

Got the same Issue today
