### ISSUE TITLE
[ERROR] TimeoutException: Message: Loading page failed, it still shows fullscreen ad.

### ISSUE THREAD

**Issue by tegger2000** [Second-Hand-Friends/kleinanzeigen-bot#41]
There is a fullscreen ad, every time I tried to offer a Fritzbox to 161/225
I tried to use ublock
      extensions: [uBlock-Origin.crx] # a list of .crx extension files to be loaded
but this seems to be wrong, ublock isn't loaded. Are there other workarounds ?

**Comment by tegger2000** [comment]
[Fehlermeldung.txt](https://github.com/Second-Hand-Friends/kleinanzeigen-bot/files/8294327/Fehlermeldung.txt)

so, neuen Artikel probiert, auch tritt der Fehler auf

**Comment by sebthom** [comment]
That is odd. I cannot reproduce it. Works fine for me. Which browser are you using?

**Comment by tegger2000** [comment]
Chromium Version 90.0.4430.212 (Developer Build) built on Debian 10.9, running on Debian 10.11 (64-bit)
