### ISSUE TITLE
WebDriverException: Message: target frame detached

### ISSUE THREAD

**Issue by DreckSoft** [Second-Hand-Friends/kleinanzeigen-bot#46]
This error basically happens every few ads:

```
[ERROR] WebDriverException: Message: target frame detached
  (Session info: chrome=99.0.4844.74)
Stacktrace:
#0 0x55d43b355e44 <unknown>
#1 0x55d43ad35bac <unknown>
#2 0x55d43ad1f02e <unknown>
#3 0x55d43ad1da23 <unknown>
#4 0x55d43ad1e068 <unknown>
#5 0x55d43ad1df94 <unknown>
#6 0x55d43ad26897 <unknown>
#7 0x55d43ad1fb26 <unknown>
#8 0x55d43ad20221 <unknown>
#9 0x55d43ad1fe1d <unknown>
#10 0x55d43ad1f226 <unknown>
#11 0x55d43ad1e651 <unknown>
#12 0x55d43ad1e3b3 <unknown>
#13 0x55d43ad37992 <unknown>
#14 0x55d43adafcf4 <unknown>
#15 0x55d43ad9bb53 <unknown>
#16 0x55d43ad64be2 <unknown>
#17 0x55d43ad6665c <unknown>
#18 0x55d43b384aaf <unknown>
#19 0x55d43b3a2102 <unknown>
#20 0x55d43b386b65 <unknown>
#21 0x55d43b3a2a86 <unknown>
#22 0x55d43b37bb61 <unknown>
#23 0x55d43b3bf537 <unknown>
#24 0x55d43b3bf716 <unknown>
#25 0x55d43b3d9d75 <unknown>
#26 0x7f9e6939d5c2 <unknown>
```
Likely some https request fails. Maybe just retry at least once before terminating the script?

**Comment by sebthom** [comment]
Is there a python stacktrace?

**Comment by DreckSoft** [comment]
Unfortunately not. Next time, i'll run it in verbose mode. I was kinda in a hurry today and just restarted the script after it crashed. But it really happened a lot.

**Comment by sebthom** [comment]
This seems to be a new issue with chrome 99, see https://groups.google.com/g/chromedriver-users/c/Z_CaHJTJnLw

**Comment by sebthom** [comment]
@DreckSoft can you please verify that the issue is gone with the latest build?

**Comment by DreckSoft** [comment]
Unfortunately currently not. I've republished all ads and now have like 3 free ads left, which I still need. I'll check as soon as possible.

**Comment by sebthom** [comment]
Nice. I am closing the issue for now. If it reappears please reopen.

**Comment by DreckSoft** [comment]
Now the same with Chrome 100...

WebDriverException: Message: target frame detached
  (Session info: chrome=100.0.4896.60)
Stacktrace:
#0 0x5579b3379ca4 <unknown>
#1 0x5579b2d4685c <unknown>
#2 0x5579b2d2f93e <unknown>
#3 0x5579b2d2e338 <unknown>
#4 0x5579b2d2e978 <unknown>
#5 0x5579b2d2e8a4 <unknown>
#6 0x5579b2d3718a <unknown>
#7 0x5579b2d30436 <unknown>
#8 0x5579b2d30b31 <unknown>
#9 0x5579b2d3072d <unknown>
#10 0x5579b2d2fb36 <unknown>
#11 0x5579b2d2ef61 <unknown>
#12 0x5579b2d2ecc3 <unknown>
#13 0x5579b2d48672 <unknown>
#14 0x5579b2dc05f4 <unknown>
#15 0x5579b2dac443 <unknown>
#16 0x5579b2d75c22 <unknown>
#17 0x5579b2d7769c <unknown>
#18 0x5579b33a85bf <unknown>
#19 0x5579b33c55bf <unknown>
#20 0x5579b33aa665 <unknown>
#21 0x5579b33c63a6 <unknown>
#22 0x5579b339ef11 <unknown>
#23 0x5579b33e4187 <unknown>
#24 0x5579b33e4366 <unknown>
#25 0x5579b33fe975 <unknown>
#26 0x7f5fab6515c2 <unknown>

**Comment by DreckSoft** [comment]
Just the same error again on the 2nd ad. Unfortunately I cannot reopen the issue.

**Comment by DreckSoft** [comment]
I just published 2 ads with verbose but "unfortunately" this time the error didn't occur. I try again next time.

**Comment by wbrtm** [comment]
Getting the same error every now and then this is what verbose mode gives me:
```
[ERROR] Traceback (most recent call last):
  File "kleinanzeigen_bot/__main__.py", line 8, in <module>
  File "kleinanzeigen_bot/__init__.py", line 594, in main
  File "kleinanzeigen_bot/__init__.py", line 76, in run
  File "kleinanzeigen_bot/__init__.py", line 370, in publish_ads
  File "kleinanzeigen_bot/__init__.py", line 378, in publish_ad
  File "kleinanzeigen_bot/__init__.py", line 549, in assert_free_ad_limit_not_reached
  File "kleinanzeigen_bot/selenium_mixin.py", line 291, in web_find
  File "kleinanzeigen_bot/selenium_mixin.py", line 258, in web_await
  File "kleinanzeigen_bot/selenium_mixin.py", line 246, in web_await
  File "selenium/webdriver/support/wait.py", line 78, in until
  File "selenium/webdriver/support/expected_conditions.py", line 64, in _predicate
  File "selenium/webdriver/remote/webdriver.py", line 1248, in find_element
  File "selenium/webdriver/remote/webdriver.py", line 425, in execute
  File "selenium/webdriver/remote/errorhandler.py", line 247, in check_response
selenium.common.exceptions.WebDriverException: Message: target frame detached
  (Session info: chrome=101.0.4951.41)
Stacktrace:
#0 0x55d3294ecaa4 <unknown>
#1 0x55d328e775e9 <unknown>
#2 0x55d328e606bd <unknown>
#3 0x55d328e5f626 <unknown>
#4 0x55d328e5fd1a <unknown>
#5 0x55d328e5fc54 <unknown>
#6 0x55d328e675f3 <unknown>
#7 0x55d328e61231 <unknown>
#8 0x55d328e619b6 <unknown>
#9 0x55d328e61560 <unknown>
#10 0x55d328e60862 <unknown>
#11 0x55d328e6022a <unknown>
#12 0x55d328e5ff54 <unknown>
#13 0x55d328e79452 <unknown>
#14 0x55d328ee73d2 <unknown>
#15 0x55d328ed47b3 <unknown>
#16 0x55d328ea3bb3 <unknown>
#17 0x55d328ea523e <unknown>
#18 0x55d32952bf8d <unknown>
#19 0x55d32952e376 <unknown>
#20 0x55d32952e05b <unknown>
#21 0x55d32952e8a2 <unknown>
#22 0x55d32951be1b <unknown>
#23 0x55d32952eb77 <unknown>
#24 0x55d329511b55 <unknown>
#25 0x55d329546ea7 <unknown>
#26 0x55d32954707e <unknown>
#27 0x55d329561da5 <unknown>
#28 0x7f98fa99c5c2 <unknown>


[150983] Failed to execute script '__main__' due to unhandled exception!
```

**Comment by sebthom** [comment]
The script already tries the operation in case that exception occurs. see https://github.com/Second-Hand-Friends/kleinanzeigen-bot/blob/5f73190a5d40b8b5822eb18108f3d72de94a74e3/kleinanzeigen_bot/selenium_mixin.py#L255
I have no idea how to solve this atm.

**Comment by DreckSoft** [comment]
Same her after 3 ads:

[ERROR] Traceback (most recent call last):
  File "kleinanzeigen_bot/__main__.py", line 8, in <module>
  File "kleinanzeigen_bot/__init__.py", line 596, in main
  File "kleinanzeigen_bot/__init__.py", line 76, in run
  File "kleinanzeigen_bot/__init__.py", line 372, in publish_ads
  File "kleinanzeigen_bot/__init__.py", line 383, in publish_ad
  File "kleinanzeigen_bot/__init__.py", line 345, in delete_ad
  File "kleinanzeigen_bot/__init__.py", line 565, in web_open
  File "kleinanzeigen_bot/selenium_mixin.py", line 291, in web_find
  File "kleinanzeigen_bot/selenium_mixin.py", line 258, in web_await
  File "kleinanzeigen_bot/selenium_mixin.py", line 246, in web_await
  File "selenium/webdriver/support/wait.py", line 78, in until
  File "selenium/webdriver/support/expected_conditions.py", line 64, in _predicate
  File "selenium/webdriver/remote/webdriver.py", line 1248, in find_element
  File "selenium/webdriver/remote/webdriver.py", line 425, in execute
  File "selenium/webdriver/remote/errorhandler.py", line 247, in check_response
selenium.common.exceptions.WebDriverException: Message: target frame detached
  (Session info: chrome=101.0.4951.54)
Stacktrace:
#0 0x563203640ab4 <unknown>
#1 0x563202fcb5e9 <unknown>
#2 0x563202fb46bd <unknown>
#3 0x563202fb3626 <unknown>
#4 0x563202fb3d1a <unknown>
#5 0x563202fb3c54 <unknown>
#6 0x563202fbb5f3 <unknown>
#7 0x563202fb5231 <unknown>
#8 0x563202fb59b6 <unknown>
#9 0x563202fb5560 <unknown>
#10 0x563202fb4862 <unknown>
#11 0x563202fb422a <unknown>
#12 0x563202fb3f54 <unknown>
#13 0x563202fcd452 <unknown>
#14 0x56320303b3d2 <unknown>
#15 0x5632030287b3 <unknown>
#16 0x563202ff7bb3 <unknown>
#17 0x563202ff923e <unknown>
#18 0x56320367ff9d <unknown>
#19 0x563203682386 <unknown>
#20 0x56320368206b <unknown>
#21 0x5632036828b2 <unknown>
#22 0x56320366fe2b <unknown>
#23 0x563203682b87 <unknown>
#24 0x563203665b65 <unknown>
#25 0x56320369aeb7 <unknown>
#26 0x56320369b08e <unknown>
#27 0x5632036b5db5 <unknown>
#28 0x7f87458545c2 <unknown>

**Comment by sebthom** [comment]
It looks like this issue will be solved in the upcoming Chrome 103, see https://bugs.chromium.org/p/chromedriver/issues/detail?id=4048#c46

**Comment by DreckSoft** [comment]
I'm currently on 102.0.5005.61. The issue is still present (seems less frequent though). Let's see how it is next month...

**Comment by sebthom** [comment]
@DreckSoft @wbrtm Chrome 103 has been released and even MS Edge is based on it now. Can you please check if the error is gone?

**Comment by DreckSoft** [comment]
The issue seems gone now. Closing this.
