### ISSUE TITLE
review/improve user documentation

### ISSUE THREAD

**Issue by sebthom** [Second-Hand-Friends/kleinanzeigen-bot#5]

**Comment by DenisLanz** [comment]
One thing that is missing in the documentation is how you get the categories, which is quite obvious from the URL but what about the sub-categories or "Typ" for example for Bicycles or Cameras ? Couldn't figure that out yet. Currently playing around with it on a mac and will be able to verify if it works on macOS (Issue #6) and support with documentation later on.

**Comment by sebthom** [comment]
I don't really know what you mean. For me everything appears in the browser as part of the URL.

![image](https://user-images.githubusercontent.com/426959/155881662-f532ab70-629f-4325-b291-76e755c7c962.png)
![image](https://user-images.githubusercontent.com/426959/155881741-ec35bd85-c7da-4258-9834-7b492369b06d.png)

**Comment by jniggemann** [comment]
In think that’s the same question I had, I’ll try to document that in a way people understand…

-- Vom Handy gesendet / sent from a mobile phone

**Comment by DenisLanz** [comment]
I'm referring to the drop-downs appearing, when selected a category:
<img width="680" alt="image" src="https://user-images.githubusercontent.com/5640155/155883840-6427652b-128c-4832-a16b-25d5fcc35be5.png">

**Comment by sebthom** [comment]
I haven't see that one before. This seems to be a separate attribute depending on the category type. That is currently not settable. It would be best if you'd open a separate feature request for this. Also if you can provide more samples of other categories where these fith-level sub-categories appear so we can check what the pattern is behind them and how to best declare them in the config.

**Comment by DenisLanz** [comment]
Sure - I'll try to find additional categories and figure out the pattern and will open a separate issue for it later. Thought it might be know, as it has been an issue with the original e-bay kleinanzeigen script as well.

**Comment by jniggemann** [comment]
Stale bot made me realize that this issue is lingering far longer than I had intended to. Sorry community, I won't find time in the near-to-mid future.
