### ISSUE TITLE
Publishing Job Ads

### ISSUE THREAD

**Issue by HessJulian** [Second-Hand-Friends/kleinanzeigen-bot#52]
Publishing Job Ads doesnt work because there is no price field.
The Code should be updated,so that it continues if there is no price field.

**Comment by sebthom** [comment]
You can now set the price-type to NOT_APPLICABLE which allows you to leave out the price. Please check if this solves your issue.

**Comment by jniggemann** [comment]
Thinking this should also apply to GIVE_AWAY, shouldn't it?
