### ISSUE TITLE
Delete ads only by ID

### ISSUE THREAD

**Issue by DreckSoft** [Second-Hand-Friends/kleinanzeigen-bot#55]
Currently the script seems to delete ads either by ID or by Title. 
Sometimes I do have two ads with the same title but different content. Now the first gets (re-)published. The second deletes the just republished ad cause it's on top of the older one and the title matches. So only the second ad remains online and the "old" second ad is still present cause the wrong one has been deleted.

I think it would be better to just delete by ad-id and ignore the title (or make it a config option)

**Comment by jniggemann** [comment]
> I think it would be better to just delete by ad-id and ignore the title (or make it a config option)

I have nut run into this issue, but I think it's a good idea.
