### ISSUE TITLE
Option to delete all ads instead of republishing

### ISSUE THREAD

**Issue by DreckSoft** [Second-Hand-Friends/kleinanzeigen-bot#56]
When I go on holiday I like to delete all ads before leaving. Unfortunately that's not available in the script. An option to delete all ads (may even regardless if a yaml file is present) would be helpful.

**Comment by DreckSoft** [comment]
This SHOULD add the delete option. Unfortunately the bot won't compile on my machine even unmodified, so I can't test it.

[delete.patch](https://github.com/Second-Hand-Friends/kleinanzeigen-bot/files/8884006/delete.patch.txt)

It basically just uses the delete part of the republishing, so it should also honor the republication date. Not sure it that's ideal but you can override with --force 

Of course it only deletes the ads present as yaml but better than noting and it does not require any complicated parsing.

**Comment by sebthom** [comment]
Thanks for the patch. It didn't work however, had to fix it. :-)
