### ISSUE TITLE
Docker image seems to be set to private

### ISSUE THREAD

**Issue by jdk-21** [Second-Hand-Friends/kleinanzeigen-bot#57]
I tried to pull the docker image like this:
`docker pull ghcr.io/second-hand-friends/kleinanzeigen-bot`

But I get an unauthorized error message:
`Using default tag: latest
Error response from daemon: Head "https://ghcr.io/v2/second-hand-friends/kleinanzeigen-bot/manifests/latest": unauthorized`

I think this happens because the image is set to private.

**Comment by sebthom** [comment]
thanks for reporting! please try again

**Comment by jdk-21** [comment]
Now, it works. Thank you.
