### ISSUE TITLE
price_type: NEGOTIABLE without a price is not supported

### ISSUE THREAD

**Issue by ChristopherLenz** [Second-Hand-Friends/kleinanzeigen-bot#61]
The script prevents me from creating an ad with following values:

```
price:
price_type: NEGOTIABLE # one of: FIXED, NEGOTIABLE, GIVE_AWAY
```

If I would use `price: 0` this would be a `GIVE_AWAY`. While using `NEGOTIABLE` without a price is a valid scenario.

see:
https://github.com/Second-Hand-Friends/kleinanzeigen-bot/blob/main/kleinanzeigen_bot/__init__.py#L244-L245

**Comment by sebthom** [comment]
Thanks for reporting!
