### ISSUE TITLE
Add images in given order

### ISSUE THREAD

**Issue by wbrtm** [Second-Hand-Friends/kleinanzeigen-bot#63]
If there are more than one source paths (wildcard patterns) given in an ad file, the images are not added in that specific order.

**Comment by sebthom** [comment]
Images are sorted by name.

**Comment by wbrtm** [comment]
Tanks for the fast reply. So this is intentional? Then I would try to tweak this only for myself.
It does make sense to me to sort by name if there is one path/pattern given. If there are more not so much. Might be specific to my use case though.

**Comment by sebthom** [comment]
You can provide a PR where the images are sorted per path if you want.

**Comment by wbrtm** [comment]
#65
