### ISSUE TITLE
Ad doesn't publish

### ISSUE THREAD

**Issue by jensgehm91** [Second-Hand-Friends/kleinanzeigen-bot#67]
Hello,
since yesterday i have the problem that the ads doesn't publish anymore.
After the as is created the upload takes longer as the waiting time, so that the window closes / the next ad will publish before the ad is fully uploaded by kleinanzeigen.

is there a way to increase this time?

**Comment by sebthom** [comment]
I cannot reproduce the issue. Publishing ads works fine. The waiting time is already at 20 seconds. If that is not enough than the issue is something else and increasing the timeout wouldn't help.
