### ISSUE TITLE
Deleting old ads does not work properly

### ISSUE THREAD

**Issue by DreckSoft** [Second-Hand-Friends/kleinanzeigen-bot#71]
After re-publishing 46ads, I now have 82 online. So most old ones got not deleted. The same issue was present in the old script. In general, deleting was unreliable but maybe this script also only checks the first page of ads for the id, so all on page 2 and following are never deleted?

**Comment by sebthom** [comment]
The script does not do any pagination. Contributions are welcome.

**Comment by DreckSoft** [comment]
I did publish a change for the old script to at least check the second page. However it still was unreliable.

**Comment by DreckSoft** [comment]
I did just look at the code. The post request is sent directly and not by clicking any buttons. So this should work in any case and when I send the request in the Browser using dev tools it does work. Very strange.

**Comment by DreckSoft** [comment]
This time, the deletion worked. Maybe the fix for deleting only by id instead by text and id also fixed this issue. Closing it, as it works now.
