### ISSUE TITLE
0.1.dev1+ga5347fc: No ad config files found

### ISSUE THREAD

**Issue by jniggemann** [Second-Hand-Friends/kleinanzeigen-bot#86]
Issue with latest pre-release on Win 10 Pro X64
```
2022-06-19 16:16:00,678 [INFO] App version: 0.1.dev1+ga5347fc
2022-06-19 16:16:00,693 [INFO] Loading config from [D:\xxx\ebay\config.yaml]...
2022-06-19 16:16:00,756 [INFO]  -> found 75 categories
2022-06-19 16:16:00,756 [INFO] Searching for ad config files...
2022-06-19 16:16:00,772 [INFO]  -> found 0 ad config files
```

Older version I had around works:
```
2022-06-19 16:19:25,602 [INFO] App version: 0.1.dev1+g2a28cc4.d20220531
2022-06-19 16:19:25,617 [INFO] Loading config from [D:\xxx\ebay\config.yaml]...
2022-06-19 16:19:25,664 [INFO]  -> found 75 categories
2022-06-19 16:19:25,664 [INFO] Searching for ad config files...
2022-06-19 16:19:25,680 [INFO]  -> found 5 ad config files
```

**Comment by sebthom** [comment]
Hmm, I cannot reproduce, seems to work fine for me.

```
[INFO] App version: 0.1.dev1+ga5347fc
[INFO] Loading config from [D:\kleinanzeigen-bot\data\config.yaml]...
[INFO]  -> found 75 categories
[INFO] Searching for ad config files...
[INFO]  -> found 4 ad config files
```

How does your config.yaml look like?

**Comment by sebthom** [comment]
Just republished some more ads, worked fine.

**Comment by domlysi** [comment]
I have the same problem running the binary and the docker instance:
```
INFO] Logging to [/mnt/data/kleinanzeigen-bot.log]...
[INFO] App version: 0.1.dev1+g7e6fbfe.d20220622
[INFO] Loading config from [/mnt/data/config.yaml]...
[INFO]  -> found 75 categories
[INFO] Searching for ad config files...
[INFO]  -> found 0 ad config files
[INFO] ############################################
[INFO] DONE: No new/outdated ads found.
[INFO] ############################################
```


```
ad_files:
  - '**/ad_*.{json,yml,yaml}'

# default values for ads, can be overwritten in each ad configuration file
ad_defaults:
  active: true
  type: OFFER # one of: OFFER, WANTED
  description:
    prefix: ''
    suffix: ''
  price_type: NEGOTIABLE # one of: FIXED, NEGOTIABLE, GIVE_AWAY, NOT_APPLICABLE
  shipping_type: SHIPPING # one of: PICKUP, SHIPPING, NOT_APPLICABLE
  contact:
    name: ''
    street: ''
    zipcode:
    phone: '' # IMPORTANT: surround phone number with quotes to prevent removal of leading zeros
  republication_interval: 7 # every X days ads should be re-published

# additional name to category ID mappings, see default list at
# https://github.com/Second-Hand-Friends/kleinanzeigen-bot/blob/main/kleinanzeigen_bot/resources/categories.yaml
# Notebooks: 161/278 # Elektronik > Notebooks
# Autoteile: 210/223/sonstige_autoteile # Auto, Rad & Boot > Autoteile & Reifen > Weitere Autoteile
categories: []

# browser configuration
browser:
  # https://peter.sh/experiments/chromium-command-line-switches/
  arguments:
    # https://stackoverflow.com/a/50725918/5116073
    - --disable-dev-shm-usage
    - --no-sandbox
    # --headless
    # --start-maximized
  binary_location: # path to custom browser executable, if not specified will be looked up on PATH
  extensions: [] # a list of .crx extension files to be loaded
  use_private_window: true
  user_data_dir: '' # see https://github.com/chromium/chromium/blob/main/docs/user_data_dir.md
  profile_name: ''

# login credentials
login:
  username: *******
  password: ******
```

**Comment by sebthom** [comment]
@domlysi where are the ad files located in this example? directly in /mnt/data/ or in a subdirectory? 
what is the pattern you used to name your ad files? E.g. `ad_XYZ.yml`

**Comment by jniggemann** [comment]
@sebthom: Error also present in version: 0.1.dev1+g7e6fbfe
Just exchanging the binary and running 0.1.dev1+g2a28cc4.d20220531 works fine.

There are only 4 commits between 0.1.dev1+g7e6fbfe and 0.1.dev1+ga5347fc, I could test if you sent me the executables.

**Comment by sebthom** [comment]
The issue was probably introduced by https://github.com/Second-Hand-Friends/kleinanzeigen-bot/commit/f924ed89d05241e3302d13693265fa128a507980 where I changed the globbing library.

However since I cannot reproduce the issue I don't know what to fix.

**Comment by jniggemann** [comment]
Could get app version: 0.1.dev1+g4e8cb9c to work, it seems to be the globbing lib indeed.  

### Before
* EXE in D:\xxx\yyy\Programme\ebay
* ads in D:\xxx\yyy\Programme\ebay\ads
* images in D:\xxx\yyy\Programme\ebay\ads\img
* config.yaml contained
```
ad_files:
  - "ads/**/ad_*.yml"
```
* ad_xxx.yml contained
```
images:
  - img\ad1_*.JPG
```

### Now (working with 0.1.dev1+g4e8cb9c)
* EXE in D:\xxx\yyy\Programme\ebay
* ads in D:\xxx\yyy\Programme\ebay\ads
* images in D:\xxx\yyy\Programme\ebay\ads  (<- all images directly in here, no longer in a subfolder)
* config.yaml contains
```
ad_files:
  - "ads/ad_*.yml"
```
* ad_xxx.yml contains
```
images:
  - ad1_*.JPG
```

Having both, the ads and img folder in D:\xxx\yyy\Programme\ebay did not work, no matter how I included the images in the ad.

I'd like it, if we could somehow keep ads and images in different folders. Helps me to better manage the files.

**Comment by sebthom** [comment]
@jniggemann better don't use backslashes in the pattern. they need to be escaped in YAML files, like `\` -> `\\`. The globbing library also expects escaped backslashes if they mean directory separator, so you would need to double escape them, like  `\` -> `\\\\`, which in your case means you'd have to use `img\\\\ad1_*.JPG`

Also, just to be clear: your previously working file structure looked like this
```yaml
D:\xxx\yyy\Programme\ebay
   |- kleinanzeigen-bot.exe
   |- config.yml  # contains:  ad_files: -"ads/**/ad_*.yml"
   |- ads\
      |- ad_1_XYZ.yml  # contains:  images: -"img/ad1_*.JPG"
      |- ads\img\
         |- ad1_some_name.JPG
```
and you run the exe in a command line window where you CDed into `D:\xxx\yyy\Programme\ebay`, like this:
```
D:\xxx\yyy\Programme\ebay> kleinanzeigen-bot.exe --config config.yml
```

**Comment by jniggemann** [comment]
Correctly using slashes instead of backslashes, there's no longer an error.
