### ISSUE TITLE
NoSuchElementException raises if  use_private_window = false

### ISSUE THREAD

**Issue by Airwave1981** [Second-Hand-Friends/kleinanzeigen-bot#87]
Hi all,

I try around with   use_private_window: false  in the config.
If this is deactivated I don't get the privacy banner, so NoSuchElementException is raised.

I put a try catch around to get over this.

Maybe someone checks this an adds to code?

Thanks

Line 330 in __init__.py

```
    # accept privacy banner
        try:
            self.web_click(By.ID, "gdpr-banner-accept")
        except NoSuchElementException:
            pass
```

**Comment by sebthom** [comment]
Thanks!
