### ISSUE TITLE
Bug with shippingcost

### ISSUE THREAD

**Issue by stkr22** [Second-Hand-Friends/kleinanzeigen-bot#91]
The shipping cost key seems to not work correctly. 

I tried like this:

`shipping_cost: 6.99`

But then the Bot enters a very long number into the corresponding field when creating the ad. This leads to an error because the pages input validations fails("value must be between 0 and 999") The bot itself then fails with some react field error.

**Comment by stkr22** [comment]
So I checked and it seems to be a rounding issue. If I remove the decimals it works fine.

**Comment by sebthom** [comment]
A PR to fix this is welcome.

**Comment by DenisLanz** [comment]
Stumbled over the same issue. Seems to be an issue with `utils.parse_decimal` - but I'm not really sure how to fix the rounding issue… as I don't really understand what parse_decimal does.
