### ISSUE TITLE
Verleihen category not working because no price can be set

### ISSUE THREAD

**Issue by ghoeffner** [Second-Hand-Friends/kleinanzeigen-bot#93]
The bot can not poste to the "Verleihen" category. I assume it is because it does not have a way to input a price.
The error is:
`1;30m[ERROR][0m [31mNoSuchElementException: Message: Element xpath='//select[@id='priceType']' not found or not clickable`

**Comment by sebthom** [comment]
You need to specify `NOT_APPLICABLE` for `PRICE_TYPE`.
