### ISSUE TITLE
(New?) Phone Verification when publishing is not handled

### ISSUE THREAD

**Issue by ghoeffner** [Second-Hand-Friends/kleinanzeigen-bot#94]
When trying to publish, I get the following notification. Unfortunately, it is not possible to complete the verification within 2 seconds manually, so it always fails and kleinanzeigen-bot crashes with 
```
[1;30m[ERROR][0m [31mTimeoutException: Message:
[0m
[11348] Failed to execute script '__main__' due to unhandled exception!
```

![image](https://user-images.githubusercontent.com/1123412/181764849-a0f6cc1f-c1cd-453c-8541-e21d248a347c.png)

**Comment by sebthom** [comment]
I haven't gotten this popup myself, so I can't fix this. PR welcome.

**Comment by DenisLanz** [comment]
Is this a one time request? Aren't you able to verify your phone number nonce and proceed with the script afterwards?

**Comment by DreckSoft** [comment]
This is one-time only. They are forcing all older accounts to reveal their phone number. New account require it from the beginning. More data-collection...

**Comment by ghoeffner** [comment]
Closing this as the popup only appeared once and never came back.
