### ISSUE TITLE
new device login validation unhandled

### ISSUE THREAD

**Issue by Airwave1981** [Second-Hand-Friends/kleinanzeigen-bot#97]
Hi @ll,

ebay kleinanzeigen again worked on it, to make it more difficult for us:

Now after login I get:
![image](https://user-images.githubusercontent.com/32637309/185338548-3cc43f8b-bef3-44a1-898c-eaeb1f8031c9.png)

(new device need to been accepted via an email button)

If you are fast enough, then you can drop the Link out of the email you get, into the browser. But afterwards the script crashes, due not handled procedure of course.

![image](https://user-images.githubusercontent.com/32637309/185340812-5b6d42e5-a179-45c8-8ef1-cbc60d7cea7c.png)

BUT(!), next time you are already logged in, when the script starts, if you setup a profile path and disabled a private window:

use_private_window: false
user_data_dir: "E:\\chrome-profile" 

Unfortunately the script starts then to relogin and the upper procedure starts again. :-(

Suggestion:

1. check if already logged in, if login is the required one, then just proceed with the classifieds.
2. if not logged in, get handle upper new page and wait for manual redirect via link (out of email) drop

(1.) Would also allow then to run the script unattended

**Comment by sebthom** [comment]
I haven't gotten this popup myself, so I can't fix this. PR welcome.

**Comment by Airwave1981** [comment]
Mhm strange. End last week it happend on every login.
Maybe it was an issue on ebays side. I had it once again no, then it was gone so far. I will monitor this...

**Comment by DreckSoft** [comment]
I think this can be closed. It's handled now.
